# Generated by Django 5.0.14 on 2025-11-24 05:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(db_index=True, help_text='Store name or identifier', max_length=100)),
                ('employee', models.CharField(db_index=True, help_text='Employee name or identifier', max_length=100)),
                ('sales_target', models.DecimalField(decimal_places=2, help_text='Target sales amount in dollars', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('actual_sales', models.DecimalField(decimal_places=2, help_text='Actual sales amount in dollars', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date', models.DateField(db_index=True, help_text='Date of the KPI measurement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'ordering': ['-date', 'store', 'employee'],
                'indexes': [models.Index(fields=['-date', 'store'], name='digital_sig_date_f1814e_idx'), models.Index(fields=['store', 'date'], name='digital_sig_store_3e0f8a_idx')],
                'unique_together': {('store', 'employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(db_index=True, help_text='Store name or identifier', max_length=100)),
                ('employee', models.CharField(db_index=True, help_text='Employee name or identifier', max_length=100)),
                ('total_sales', models.DecimalField(decimal_places=2, help_text='Total sales amount in dollars', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date', models.DateField(db_index=True, help_text='Date of the sales data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sales Data',
                'verbose_name_plural': 'Sales Data',
                'ordering': ['-date', 'store', 'employee'],
                'indexes': [models.Index(fields=['-date', 'store'], name='digital_sig_date_57a875_idx'), models.Index(fields=['store', 'date'], name='digital_sig_store_9aa37b_idx')],
                'unique_together': {('store', 'employee', 'date')},
            },
        ),
    ]
