# Generated by Django 5.2.3 on 2025-11-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name for this screen (e.g., 'Store 1 Main Display')", max_length=200)),
                ('slug', models.SlugField(help_text='URL-safe identifier for this screen (used in /signage/play/<slug>/)', max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active screens can be played')),
                ('layout_type', models.CharField(choices=[('test', 'Test Layout')], default='test', help_text='Screen layout template to use', max_length=50)),
                ('html_override', models.TextField(blank=True, help_text='Custom HTML content (for advanced use)')),
                ('css_override', models.TextField(blank=True, help_text='Custom CSS styles (for advanced use)')),
                ('js_override', models.TextField(blank=True, help_text='Custom JavaScript code (for advanced use)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Screen',
                'verbose_name_plural': 'Screens',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug', 'is_active'], name='digital_sig_slug_c7df1b_idx')],
            },
        ),
    ]
