# Generated by Django 5.2.3 on 2025-11-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0002_screen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name for this screen design (e.g., 'Sales Dashboard Q1')", max_length=200)),
                ('slug', models.SlugField(help_text='URL-safe identifier for this design', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this screen design displays and its purpose')),
                ('html_code', models.TextField(blank=True, help_text='HTML code for the screen content')),
                ('css_code', models.TextField(blank=True, help_text='CSS code for styling the screen')),
                ('js_code', models.TextField(blank=True, help_text='JavaScript code for dynamic behavior')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this design (usage instructions, data sources, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this design is actively being used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Screen Design',
                'verbose_name_plural': 'Screen Designs',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['slug', 'is_active'], name='digital_sig_slug_e31e1f_idx'), models.Index(fields=['-updated_at'], name='digital_sig_updated_f64ef9_idx')],
            },
        ),
    ]
