# Generated by Django 5.2.3 on 2025-11-26 00:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0003_screendesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this playlist', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Descriptive name for this playlist (e.g., 'Store 1 Rotation')", max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe identifier for this playlist', max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this playlist is actively being used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this device', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text="Human-readable device name (e.g., 'Store 1 Main Display')", max_length=200)),
                ('registration_code', models.CharField(blank=True, help_text="Short code for device registration (e.g., 'ABC123')", max_length=8, null=True, unique=True)),
                ('registered', models.BooleanField(default=False, help_text='Whether this device has been registered and configured')),
                ('location', models.CharField(blank=True, help_text="Physical location of this device (e.g., 'Store 12, Front Counter')", max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this device')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Last time this device checked in')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_screen', models.ForeignKey(blank=True, help_text='Single screen assigned to this device (used if no playlist assigned)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital_signage.screendesign')),
                ('assigned_playlist', models.ForeignKey(blank=True, help_text='Playlist assigned to this device (takes precedence over single screen)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital_signage.playlist')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['registration_code'], name='digital_sig_registr_0d778a_idx'), models.Index(fields=['registered'], name='digital_sig_registe_d6fc1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers shown first)')),
                ('duration_seconds', models.PositiveIntegerField(default=30, help_text='How long to display this screen (in seconds)', validators=[django.core.validators.MinValueValidator(1)])),
                ('playlist', models.ForeignKey(help_text='Playlist this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='digital_signage.playlist')),
                ('screen', models.ForeignKey(help_text='Screen design to display', on_delete=django.db.models.deletion.CASCADE, to='digital_signage.screendesign')),
            ],
            options={
                'verbose_name': 'Playlist Item',
                'verbose_name_plural': 'Playlist Items',
                'ordering': ['playlist', 'order'],
                'unique_together': {('playlist', 'order')},
            },
        ),
    ]
