# Generated by Django

from django.db import migrations


def create_welcome_screen(apps, schema_editor):
    """Create a default welcome screen for newly registered devices."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')

    # Check if welcome screen already exists
    if not ScreenDesign.objects.filter(slug='welcome-screen').exists():
        ScreenDesign.objects.create(
            name='Welcome Screen',
            slug='welcome-screen',
            description='Default welcome screen shown after device registration',
            html_code='''<div class="welcome-container">
    <div class="logo">
        <div class="grid-icon"></div>
    </div>
    <h1>Welcome to The Grid</h1>
    <p class="subtitle">Digital Signage System</p>
    <div class="status">
        <div class="status-indicator"></div>
        <span>Device Successfully Registered</span>
    </div>
    <p class="instructions">Your administrator will assign content shortly</p>
</div>''',
            css_code='''body {
    margin: 0;
    padding: 0;
    background: linear-gradient(135deg, #0a0a1a 0%, #1a1a2e 50%, #0a0a1a 100%);
    font-family: 'Suisse Intl', 'Inter', -apple-system, sans-serif;
    display: flex;
    align-items: center;
    justify-content: center;
    min-height: 100vh;
    overflow: hidden;
}

body::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background:
        linear-gradient(90deg, rgba(155, 89, 255, 0.03) 1px, transparent 1px),
        linear-gradient(0deg, rgba(155, 89, 255, 0.03) 1px, transparent 1px);
    background-size: 50px 50px;
    animation: gridMove 20s linear infinite;
}

@keyframes gridMove {
    0% { transform: translate(0, 0); }
    100% { transform: translate(50px, 50px); }
}

.welcome-container {
    position: relative;
    z-index: 1;
    text-align: center;
    max-width: 800px;
    padding: 3rem;
}

.logo {
    margin-bottom: 2rem;
}

.grid-icon {
    width: 120px;
    height: 120px;
    margin: 0 auto;
    border: 3px solid #9B59FF;
    background: rgba(155, 89, 255, 0.05);
    position: relative;
    box-shadow:
        0 0 40px rgba(155, 89, 255, 0.3),
        inset 0 0 40px rgba(155, 89, 255, 0.1);
}

.grid-icon::before,
.grid-icon::after {
    content: '';
    position: absolute;
    background: #9B59FF;
}

.grid-icon::before {
    top: 50%;
    left: 0;
    right: 0;
    height: 3px;
    transform: translateY(-50%);
}

.grid-icon::after {
    left: 50%;
    top: 0;
    bottom: 0;
    width: 3px;
    transform: translateX(-50%);
}

h1 {
    font-size: 4rem;
    font-weight: 700;
    color: #ffffff;
    margin: 0 0 1rem 0;
    letter-spacing: -0.02em;
    text-transform: uppercase;
}

.subtitle {
    font-size: 1.5rem;
    color: rgba(255, 255, 255, 0.6);
    margin: 0 0 3rem 0;
    letter-spacing: 0.1em;
    text-transform: uppercase;
    font-family: 'Suisse Intl Mono', monospace;
}

.status {
    display: inline-flex;
    align-items: center;
    gap: 1rem;
    padding: 1rem 2rem;
    background: rgba(0, 240, 255, 0.1);
    border: 1px solid rgba(0, 240, 255, 0.3);
    border-radius: 0;
    margin-bottom: 2rem;
}

.status-indicator {
    width: 12px;
    height: 12px;
    background: #00F0FF;
    border-radius: 50%;
    box-shadow: 0 0 20px #00F0FF;
    animation: pulse 2s ease-in-out infinite;
}

@keyframes pulse {
    0%, 100% { opacity: 1; }
    50% { opacity: 0.5; }
}

.status span {
    color: #00F0FF;
    font-family: 'Suisse Intl Mono', monospace;
    font-size: 1rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
}

.instructions {
    font-size: 1.2rem;
    color: rgba(255, 255, 255, 0.5);
    margin: 0;
    font-family: 'Suisse Intl Mono', monospace;
}''',
            js_code='',
            is_active=True
        )


def reverse_create_welcome_screen(apps, schema_editor):
    """Remove the welcome screen."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')
    ScreenDesign.objects.filter(slug='welcome-screen').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0004_playlist_device_playlistitem'),
    ]

    operations = [
        migrations.RunPython(create_welcome_screen, reverse_create_welcome_screen),
    ]
