# Generated by Django

from django.db import migrations


def fix_welcome_screen_css(apps, schema_editor):
    """Fix horizontal centering of welcome screen."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')

    try:
        welcome = ScreenDesign.objects.get(slug='welcome-screen')
        # Update CSS to add margin: 0 auto for horizontal centering
        welcome.css_code = welcome.css_code.replace(
            '''.welcome-container {
    position: relative;
    z-index: 1;
    text-align: center;
    max-width: 800px;
    padding: 3rem;
}''',
            '''.welcome-container {
    position: relative;
    z-index: 1;
    text-align: center;
    max-width: 800px;
    padding: 3rem;
    margin: 0 auto;
    width: 100%;
}'''
        )
        welcome.save()
    except ScreenDesign.DoesNotExist:
        pass  # Welcome screen doesn't exist, skip


def reverse_fix(apps, schema_editor):
    """Reverse the CSS fix."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')

    try:
        welcome = ScreenDesign.objects.get(slug='welcome-screen')
        welcome.css_code = welcome.css_code.replace(
            '''.welcome-container {
    position: relative;
    z-index: 1;
    text-align: center;
    max-width: 800px;
    padding: 3rem;
    margin: 0 auto;
    width: 100%;
}''',
            '''.welcome-container {
    position: relative;
    z-index: 1;
    text-align: center;
    max-width: 800px;
    padding: 3rem;
}'''
        )
        welcome.save()
    except ScreenDesign.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0005_add_welcome_screen'),
    ]

    operations = [
        migrations.RunPython(fix_welcome_screen_css, reverse_fix),
    ]
