# Generated by Django 5.0.14 on 2025-11-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0006_fix_welcome_screen_centering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True, help_text='Last time this device checked in (updated when device polls for config)'),
        ),
    ]
