# Generated by Django 5.0.14 on 2025-11-27 03:57

import digital_signage.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0007_fix_last_seen_auto_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this media asset', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name for this media (e.g., 'Holiday Sale Banner')", max_length=200)),
                ('slug', models.SlugField(help_text='URL-safe identifier for this media', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description or notes about this media')),
                ('file', models.FileField(help_text='The image or video file', upload_to=digital_signage.models.media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'mp4', 'webm', 'mov', 'avi'])])),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], help_text='Type of media asset (auto-detected from file extension)', max_length=10)),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail image (auto-generated for videos)', null=True, upload_to=digital_signage.models.thumbnail_upload_path)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duration in seconds (for videos only)', null=True)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Width in pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height in pixels', null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this asset is available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Asset',
                'verbose_name_plural': 'Media Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='item_type',
            field=models.CharField(choices=[('screen', 'Screen Design'), ('media', 'Media Asset')], default='screen', help_text='Type of content (screen design or media)', max_length=10),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=30, help_text='How long to display this item (in seconds). For videos, set to 0 to use video duration.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='screen',
            field=models.ForeignKey(blank=True, help_text="Screen design to display (if item_type is 'screen')", null=True, on_delete=django.db.models.deletion.CASCADE, to='digital_signage.screendesign'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='media_asset',
            field=models.ForeignKey(blank=True, help_text="Media asset to display (if item_type is 'media')", null=True, on_delete=django.db.models.deletion.CASCADE, to='digital_signage.mediaasset'),
        ),
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this folder', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Folder name (e.g., 'Store Promotions', 'Product Images')", max_length=200)),
                ('slug', models.SlugField(help_text='URL-safe identifier for this folder', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this folder contains')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent folder (for nested organization)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='digital_signage.mediafolder')),
            ],
            options={
                'verbose_name': 'Media Folder',
                'verbose_name_plural': 'Media Folders',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Folder this asset belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='digital_signage.mediafolder'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['asset_type', 'is_active'], name='digital_sig_asset_t_269317_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['folder', '-created_at'], name='digital_sig_folder__994b3c_idx'),
        ),
    ]
