# Generated by Django 5.0.14 on 2025-11-27 19:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0008_add_media_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this group', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Group/location name (e.g., 'Store 12', 'Head Office')", max_length=200)),
                ('slug', models.SlugField(help_text='URL-safe identifier for this group', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description or notes about this location/group')),
                ('address', models.CharField(blank=True, help_text='Physical address of this location (optional)', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this group is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device Group',
                'verbose_name_plural': 'Device Groups',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, help_text="Specific location within the group (e.g., 'Front Counter', 'Break Room')", max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Group/location this device belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='digital_signage.devicegroup'),
        ),
    ]
