# Generated by Django 5.0.14 on 2025-11-27 22:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0009_add_device_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesBoardSummary',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=200)),
                ('report_date', models.DateField()),
                ('current_day_date', models.DateField(help_text="Actual date used for 'today' metrics (may lag by 1 day)", null=True)),
                ('week_start_date', models.DateField(null=True)),
                ('month_start_date', models.DateField(null=True)),
                ('today_profit', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('today_invoiced', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('today_invoice_count', models.IntegerField(null=True)),
                ('today_devices_sold', models.IntegerField(null=True)),
                ('today_device_profit', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('wtd_profit', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('wtd_invoiced', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('wtd_invoice_count', models.IntegerField(null=True)),
                ('wtd_devices_sold', models.IntegerField(null=True)),
                ('wtd_device_profit', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('mtd_profit', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('mtd_invoiced', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('mtd_invoice_count', models.IntegerField(null=True)),
                ('mtd_devices_sold', models.IntegerField(null=True)),
                ('mtd_device_profit', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('last_updated', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Sales Board Summary',
                'verbose_name_plural': 'Sales Board Summaries',
                'db_table': 'sales_board_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this data source', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name for this data source (e.g., 'Today Top 5 Profit')", max_length=200)),
                ('key', models.SlugField(help_text="Unique key used in templates (e.g., 'today_top5_profit' -> {{sales.today_top5_profit}})", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what data this source provides')),
                ('data_type', models.CharField(choices=[('sales', 'Sales Data'), ('inventory', 'Inventory Data'), ('custom', 'Custom Query')], default='sales', help_text='Type of data this source provides', max_length=20)),
                ('query_config', models.JSONField(default=dict, help_text='Query configuration (metric, period, limit, ordering, etc.)')),
                ('refresh_interval', models.PositiveIntegerField(choices=[(60, '1 minute'), (300, '5 minutes'), (900, '15 minutes'), (1800, '30 minutes'), (3600, '1 hour')], default=300, help_text='How often to refresh the cached data (in seconds)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this data source is available for use')),
                ('sample_output', models.JSONField(blank=True, help_text='Sample output for documentation purposes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'ordering': ['data_type', 'name'],
            },
        ),
    ]
