# Generated by Django 4.2

from django.db import migrations


def create_sample_designs(apps, schema_editor):
    """Create sample screen designs for sales leaderboards."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')

    # Sample 1: Top 5 Profit Leaderboard
    ScreenDesign.objects.create(
        name="Top 5 Profit Leaderboard",
        slug="top-5-profit-leaderboard",
        description="Displays top 5 stores ranked by profit for today. Clean, dark design optimized for TV displays.",
        html_code="""<div class="leaderboard-container">
    <div class="leaderboard-header">
        <h1 class="leaderboard-title">Today's Top Performers</h1>
        <p class="leaderboard-subtitle">Profit Leaderboard</p>
    </div>

    <div class="total-section">
        <span class="total-label">Total Profit</span>
        <span class="total-value">{{sales.today.totals.profit}}</span>
    </div>

    <div class="leaderboard-list">
        {{#each sales.today.top5_profit}}
        <div class="leaderboard-item rank-{{rank}}">
            <div class="rank-badge">{{rank}}</div>
            <div class="store-info">
                <span class="store-name">{{store_name}}</span>
            </div>
            <div class="store-value">{{value}}</div>
        </div>
        {{/each}}
    </div>

    <div class="leaderboard-footer">
        <span class="update-label">Data refreshes every 5 minutes</span>
    </div>
</div>""",
        css_code="""/* Leaderboard Container */
.leaderboard-container {
    display: flex;
    flex-direction: column;
    min-height: 100vh;
    padding: 3rem;
    background: linear-gradient(135deg, #0a0a12 0%, #1a1a2e 50%, #0a0a12 100%);
}

/* Header */
.leaderboard-header {
    text-align: center;
    margin-bottom: 2rem;
}

.leaderboard-title {
    font-size: 3.5rem;
    font-weight: 700;
    color: #ffffff;
    margin: 0;
    text-transform: uppercase;
    letter-spacing: 0.1em;
}

.leaderboard-subtitle {
    font-size: 1.5rem;
    color: #00f0ff;
    margin: 0.5rem 0 0 0;
    font-weight: 500;
}

/* Total Section */
.total-section {
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 1.5rem;
    padding: 1.5rem 2rem;
    background: rgba(0, 240, 255, 0.1);
    border: 1px solid rgba(0, 240, 255, 0.3);
    margin-bottom: 2rem;
}

.total-label {
    font-size: 1.25rem;
    color: rgba(255, 255, 255, 0.7);
    text-transform: uppercase;
    letter-spacing: 0.05em;
}

.total-value {
    font-size: 3rem;
    font-weight: 700;
    color: #00f0ff;
}

/* Leaderboard List */
.leaderboard-list {
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 1rem;
}

.leaderboard-item {
    display: flex;
    align-items: center;
    padding: 1.5rem 2rem;
    background: rgba(255, 255, 255, 0.03);
    border: 1px solid rgba(255, 255, 255, 0.1);
    transition: all 0.3s ease;
}

/* Rank-specific styling */
.leaderboard-item.rank-1 {
    background: linear-gradient(90deg, rgba(255, 215, 0, 0.15) 0%, rgba(255, 215, 0, 0.05) 100%);
    border-color: rgba(255, 215, 0, 0.4);
}

.leaderboard-item.rank-2 {
    background: linear-gradient(90deg, rgba(192, 192, 192, 0.1) 0%, rgba(192, 192, 192, 0.03) 100%);
    border-color: rgba(192, 192, 192, 0.3);
}

.leaderboard-item.rank-3 {
    background: linear-gradient(90deg, rgba(205, 127, 50, 0.1) 0%, rgba(205, 127, 50, 0.03) 100%);
    border-color: rgba(205, 127, 50, 0.3);
}

.rank-badge {
    width: 60px;
    height: 60px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 1.75rem;
    font-weight: 700;
    color: #fff;
    background: rgba(100, 52, 248, 0.3);
    border: 2px solid rgba(100, 52, 248, 0.5);
    margin-right: 1.5rem;
}

.rank-1 .rank-badge {
    background: rgba(255, 215, 0, 0.3);
    border-color: #ffd700;
    color: #ffd700;
}

.rank-2 .rank-badge {
    background: rgba(192, 192, 192, 0.3);
    border-color: #c0c0c0;
    color: #c0c0c0;
}

.rank-3 .rank-badge {
    background: rgba(205, 127, 50, 0.3);
    border-color: #cd7f32;
    color: #cd7f32;
}

.store-info {
    flex: 1;
}

.store-name {
    font-size: 1.75rem;
    font-weight: 600;
    color: #ffffff;
}

.store-value {
    font-size: 2.25rem;
    font-weight: 700;
    color: #4ade80;
}

/* Footer */
.leaderboard-footer {
    text-align: center;
    padding-top: 2rem;
    border-top: 1px solid rgba(255, 255, 255, 0.1);
    margin-top: 2rem;
}

.update-label {
    font-size: 0.875rem;
    color: rgba(255, 255, 255, 0.4);
    text-transform: uppercase;
    letter-spacing: 0.1em;
}""",
        js_code="",
        notes="Sample leaderboard design showing top 5 stores by profit. Uses dynamic data from sales.today.top5_profit array.",
        is_active=True,
    )

    # Sample 2: Full Company Dashboard
    ScreenDesign.objects.create(
        name="Company Sales Dashboard",
        slug="company-sales-dashboard",
        description="Comprehensive dashboard showing today's totals, WTD, MTD and top performers.",
        html_code="""<div class="dashboard-container">
    <div class="dashboard-header">
        <h1 class="company-name">Jump.ca Sales</h1>
        <p class="dashboard-date">Live Performance</p>
    </div>

    <div class="metrics-grid">
        <div class="metric-card">
            <div class="metric-label">Today's Profit</div>
            <div class="metric-value primary">{{sales.today.totals.profit}}</div>
            <div class="metric-sub">{{sales.today.totals.invoice_count}} invoices</div>
        </div>

        <div class="metric-card">
            <div class="metric-label">Week to Date</div>
            <div class="metric-value">{{sales.wtd.totals.profit}}</div>
            <div class="metric-sub">{{sales.wtd.totals.devices}} devices</div>
        </div>

        <div class="metric-card">
            <div class="metric-label">Month to Date</div>
            <div class="metric-value">{{sales.mtd.totals.profit}}</div>
            <div class="metric-sub">{{sales.mtd.totals.devices}} devices</div>
        </div>

        <div class="metric-card">
            <div class="metric-label">Today's Devices</div>
            <div class="metric-value accent">{{sales.today.totals.devices}}</div>
            <div class="metric-sub">units sold</div>
        </div>
    </div>

    <div class="leaderboard-section">
        <h2 class="section-title">Top 5 Today</h2>
        <div class="mini-leaderboard">
            {{#each sales.today.top5_profit}}
            <div class="mini-item">
                <span class="mini-rank">#{{rank}}</span>
                <span class="mini-name">{{store_name}}</span>
                <span class="mini-value">{{value}}</span>
            </div>
            {{/each}}
        </div>
    </div>
</div>""",
        css_code="""/* Dashboard Container */
.dashboard-container {
    min-height: 100vh;
    padding: 2.5rem;
    background: linear-gradient(180deg, #0f0f1a 0%, #1a1a2e 100%);
}

/* Header */
.dashboard-header {
    text-align: center;
    margin-bottom: 3rem;
}

.company-name {
    font-size: 4rem;
    font-weight: 800;
    color: #ffffff;
    margin: 0;
    background: linear-gradient(90deg, #00f0ff, #9B59FF);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
}

.dashboard-date {
    font-size: 1.25rem;
    color: rgba(255, 255, 255, 0.5);
    margin: 0.5rem 0 0 0;
    text-transform: uppercase;
    letter-spacing: 0.2em;
}

/* Metrics Grid */
.metrics-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 1.5rem;
    margin-bottom: 3rem;
}

.metric-card {
    background: rgba(255, 255, 255, 0.03);
    border: 1px solid rgba(255, 255, 255, 0.1);
    padding: 2rem;
    text-align: center;
}

.metric-label {
    font-size: 1rem;
    color: rgba(255, 255, 255, 0.6);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1rem;
}

.metric-value {
    font-size: 3rem;
    font-weight: 700;
    color: #ffffff;
}

.metric-value.primary {
    color: #00f0ff;
}

.metric-value.accent {
    color: #9B59FF;
}

.metric-sub {
    font-size: 0.875rem;
    color: rgba(255, 255, 255, 0.4);
    margin-top: 0.5rem;
}

/* Leaderboard Section */
.leaderboard-section {
    background: rgba(255, 255, 255, 0.02);
    border: 1px solid rgba(255, 255, 255, 0.08);
    padding: 2rem;
}

.section-title {
    font-size: 1.5rem;
    font-weight: 600;
    color: #ffffff;
    margin: 0 0 1.5rem 0;
    text-transform: uppercase;
    letter-spacing: 0.1em;
}

.mini-leaderboard {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
}

.mini-item {
    display: flex;
    align-items: center;
    padding: 1rem 1.5rem;
    background: rgba(0, 0, 0, 0.2);
    border-left: 3px solid #6434f8;
}

.mini-item:first-child {
    border-left-color: #ffd700;
    background: rgba(255, 215, 0, 0.05);
}

.mini-rank {
    font-size: 1.25rem;
    font-weight: 700;
    color: #6434f8;
    width: 60px;
}

.mini-item:first-child .mini-rank {
    color: #ffd700;
}

.mini-name {
    flex: 1;
    font-size: 1.25rem;
    color: #ffffff;
}

.mini-value {
    font-size: 1.5rem;
    font-weight: 700;
    color: #4ade80;
}""",
        js_code="",
        notes="Comprehensive dashboard showing multiple metrics. Good for office displays or management screens.",
        is_active=True,
    )


def remove_sample_designs(apps, schema_editor):
    """Remove sample screen designs."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')
    ScreenDesign.objects.filter(slug__in=[
        'top-5-profit-leaderboard',
        'company-sales-dashboard',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0010_add_dynamic_data_models'),
    ]

    operations = [
        migrations.RunPython(create_sample_designs, remove_sample_designs),
    ]
