# Generated by Django 4.2

from django.db import migrations


def update_sample_designs_responsive(apps, schema_editor):
    """Update sample screen designs with responsive viewport-based sizing."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')

    # Update Top 5 Profit Leaderboard with responsive CSS
    try:
        leaderboard = ScreenDesign.objects.get(slug='top-5-profit-leaderboard')
        leaderboard.css_code = """/* Responsive Leaderboard - scales to any screen size */
/* Using viewport units (vw/vh) for TV displays */

.leaderboard-container {
    display: flex;
    flex-direction: column;
    height: 100vh;
    width: 100vw;
    padding: 3vh 4vw;
    background: linear-gradient(135deg, #0a0a12 0%, #1a1a2e 50%, #0a0a12 100%);
    box-sizing: border-box;
    overflow: hidden;
}

/* Header */
.leaderboard-header {
    text-align: center;
    margin-bottom: 2vh;
    flex-shrink: 0;
}

.leaderboard-title {
    font-size: clamp(2rem, 5vw, 4rem);
    font-weight: 700;
    color: #ffffff;
    margin: 0;
    text-transform: uppercase;
    letter-spacing: 0.1em;
}

.leaderboard-subtitle {
    font-size: clamp(1rem, 2.5vw, 2rem);
    color: #00f0ff;
    margin: 0.5vh 0 0 0;
    font-weight: 500;
}

/* Total Section */
.total-section {
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 2vw;
    padding: 2vh 3vw;
    background: rgba(0, 240, 255, 0.1);
    border: 1px solid rgba(0, 240, 255, 0.3);
    margin-bottom: 2vh;
    flex-shrink: 0;
}

.total-label {
    font-size: clamp(0.9rem, 1.8vw, 1.5rem);
    color: rgba(255, 255, 255, 0.7);
    text-transform: uppercase;
    letter-spacing: 0.05em;
}

.total-value {
    font-size: clamp(2rem, 5vw, 4rem);
    font-weight: 700;
    color: #00f0ff;
}

/* Leaderboard List */
.leaderboard-list {
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 1.5vh;
    min-height: 0;
}

.leaderboard-item {
    display: flex;
    align-items: center;
    padding: 2vh 2vw;
    background: rgba(255, 255, 255, 0.03);
    border: 1px solid rgba(255, 255, 255, 0.1);
    transition: all 0.3s ease;
    flex: 1;
}

/* Rank-specific styling */
.leaderboard-item.rank-1 {
    background: linear-gradient(90deg, rgba(255, 215, 0, 0.15) 0%, rgba(255, 215, 0, 0.05) 100%);
    border-color: rgba(255, 215, 0, 0.4);
}

.leaderboard-item.rank-2 {
    background: linear-gradient(90deg, rgba(192, 192, 192, 0.1) 0%, rgba(192, 192, 192, 0.03) 100%);
    border-color: rgba(192, 192, 192, 0.3);
}

.leaderboard-item.rank-3 {
    background: linear-gradient(90deg, rgba(205, 127, 50, 0.1) 0%, rgba(205, 127, 50, 0.03) 100%);
    border-color: rgba(205, 127, 50, 0.3);
}

.rank-badge {
    width: clamp(40px, 6vw, 80px);
    height: clamp(40px, 6vw, 80px);
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: clamp(1.2rem, 2.5vw, 2.5rem);
    font-weight: 700;
    color: #fff;
    background: rgba(100, 52, 248, 0.3);
    border: 2px solid rgba(100, 52, 248, 0.5);
    margin-right: 2vw;
    flex-shrink: 0;
}

.rank-1 .rank-badge {
    background: rgba(255, 215, 0, 0.3);
    border-color: #ffd700;
    color: #ffd700;
}

.rank-2 .rank-badge {
    background: rgba(192, 192, 192, 0.3);
    border-color: #c0c0c0;
    color: #c0c0c0;
}

.rank-3 .rank-badge {
    background: rgba(205, 127, 50, 0.3);
    border-color: #cd7f32;
    color: #cd7f32;
}

.store-info {
    flex: 1;
    min-width: 0;
}

.store-name {
    font-size: clamp(1.2rem, 2.8vw, 2.5rem);
    font-weight: 600;
    color: #ffffff;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.store-value {
    font-size: clamp(1.5rem, 3.5vw, 3rem);
    font-weight: 700;
    color: #4ade80;
    flex-shrink: 0;
}

/* Footer */
.leaderboard-footer {
    text-align: center;
    padding-top: 2vh;
    border-top: 1px solid rgba(255, 255, 255, 0.1);
    margin-top: auto;
    flex-shrink: 0;
}

.update-label {
    font-size: clamp(0.7rem, 1.2vw, 1rem);
    color: rgba(255, 255, 255, 0.4);
    text-transform: uppercase;
    letter-spacing: 0.1em;
}"""
        leaderboard.save()
    except ScreenDesign.DoesNotExist:
        pass

    # Update Company Sales Dashboard with responsive CSS
    try:
        dashboard = ScreenDesign.objects.get(slug='company-sales-dashboard')
        dashboard.css_code = """/* Responsive Dashboard - scales to any screen size */
/* Using viewport units (vw/vh) for TV displays */

.dashboard-container {
    height: 100vh;
    width: 100vw;
    padding: 3vh 4vw;
    background: linear-gradient(180deg, #0f0f1a 0%, #1a1a2e 100%);
    box-sizing: border-box;
    overflow: hidden;
    display: flex;
    flex-direction: column;
}

/* Header */
.dashboard-header {
    text-align: center;
    margin-bottom: 3vh;
    flex-shrink: 0;
}

.company-name {
    font-size: clamp(2.5rem, 6vw, 5rem);
    font-weight: 800;
    color: #ffffff;
    margin: 0;
    background: linear-gradient(90deg, #00f0ff, #9B59FF);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
}

.dashboard-date {
    font-size: clamp(0.9rem, 2vw, 1.5rem);
    color: rgba(255, 255, 255, 0.5);
    margin: 1vh 0 0 0;
    text-transform: uppercase;
    letter-spacing: 0.2em;
}

/* Metrics Grid */
.metrics-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 2vw;
    margin-bottom: 3vh;
    flex-shrink: 0;
}

.metric-card {
    background: rgba(255, 255, 255, 0.03);
    border: 1px solid rgba(255, 255, 255, 0.1);
    padding: 3vh 2vw;
    text-align: center;
}

.metric-label {
    font-size: clamp(0.7rem, 1.3vw, 1.2rem);
    color: rgba(255, 255, 255, 0.6);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1.5vh;
}

.metric-value {
    font-size: clamp(1.8rem, 4vw, 4rem);
    font-weight: 700;
    color: #ffffff;
}

.metric-value.primary {
    color: #00f0ff;
}

.metric-value.accent {
    color: #9B59FF;
}

.metric-sub {
    font-size: clamp(0.6rem, 1.1vw, 1rem);
    color: rgba(255, 255, 255, 0.4);
    margin-top: 1vh;
}

/* Leaderboard Section */
.leaderboard-section {
    background: rgba(255, 255, 255, 0.02);
    border: 1px solid rgba(255, 255, 255, 0.08);
    padding: 2vh 2vw;
    flex: 1;
    display: flex;
    flex-direction: column;
    min-height: 0;
}

.section-title {
    font-size: clamp(1rem, 2vw, 1.8rem);
    font-weight: 600;
    color: #ffffff;
    margin: 0 0 2vh 0;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    flex-shrink: 0;
}

.mini-leaderboard {
    display: flex;
    flex-direction: column;
    gap: 1vh;
    flex: 1;
    min-height: 0;
}

.mini-item {
    display: flex;
    align-items: center;
    padding: 1.5vh 2vw;
    background: rgba(0, 0, 0, 0.2);
    border-left: 3px solid #6434f8;
    flex: 1;
}

.mini-item:first-child {
    border-left-color: #ffd700;
    background: rgba(255, 215, 0, 0.05);
}

.mini-rank {
    font-size: clamp(1rem, 1.8vw, 1.5rem);
    font-weight: 700;
    color: #6434f8;
    width: 6vw;
    min-width: 50px;
    flex-shrink: 0;
}

.mini-item:first-child .mini-rank {
    color: #ffd700;
}

.mini-name {
    flex: 1;
    font-size: clamp(1rem, 1.8vw, 1.5rem);
    color: #ffffff;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    min-width: 0;
}

.mini-value {
    font-size: clamp(1.2rem, 2.2vw, 2rem);
    font-weight: 700;
    color: #4ade80;
    flex-shrink: 0;
}"""
        dashboard.save()
    except ScreenDesign.DoesNotExist:
        pass


def revert_sample_designs(apps, schema_editor):
    """Revert to original non-responsive CSS (no-op since we're just updating)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0011_add_sample_screen_designs'),
    ]

    operations = [
        migrations.RunPython(update_sample_designs_responsive, revert_sample_designs),
    ]
