# Generated by Django 4.2

from django.db import migrations


def fix_responsive_scaling(apps, schema_editor):
    """Fix responsive scaling to work on all screen sizes from 14" laptops to 100" TVs."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')

    # Update Top 5 Profit Leaderboard - truly responsive
    try:
        leaderboard = ScreenDesign.objects.get(slug='top-5-profit-leaderboard')
        leaderboard.css_code = """/* Responsive Leaderboard - fits any screen from 14" to 100" */
/* All sizing based on viewport to guarantee fit */

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

.leaderboard-container {
    display: flex;
    flex-direction: column;
    height: 100vh;
    width: 100vw;
    padding: 2vh 3vw;
    background: linear-gradient(135deg, #0a0a12 0%, #1a1a2e 50%, #0a0a12 100%);
    overflow: hidden;
}

/* Header - 12% of viewport height */
.leaderboard-header {
    text-align: center;
    height: 12vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
    flex-shrink: 0;
}

.leaderboard-title {
    font-size: 4.5vh;
    font-weight: 700;
    color: #ffffff;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    line-height: 1.2;
}

.leaderboard-subtitle {
    font-size: 2.5vh;
    color: #00f0ff;
    font-weight: 500;
    margin-top: 0.5vh;
}

/* Total Section - 10% of viewport height */
.total-section {
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 3vw;
    height: 10vh;
    background: rgba(0, 240, 255, 0.1);
    border: 1px solid rgba(0, 240, 255, 0.3);
    margin: 1vh 0 2vh 0;
    flex-shrink: 0;
}

.total-label {
    font-size: 2vh;
    color: rgba(255, 255, 255, 0.7);
    text-transform: uppercase;
    letter-spacing: 0.05em;
}

.total-value {
    font-size: 5vh;
    font-weight: 700;
    color: #00f0ff;
}

/* Leaderboard List - remaining space (~70vh minus footer) */
.leaderboard-list {
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 1vh;
    min-height: 0;
    overflow: hidden;
}

/* Each item gets equal share of available space */
.leaderboard-item {
    display: flex;
    align-items: center;
    padding: 0 2vw;
    background: rgba(255, 255, 255, 0.03);
    border: 1px solid rgba(255, 255, 255, 0.1);
    flex: 1;
    min-height: 0;
}

/* Rank-specific styling */
.leaderboard-item.rank-1 {
    background: linear-gradient(90deg, rgba(255, 215, 0, 0.15) 0%, rgba(255, 215, 0, 0.05) 100%);
    border-color: rgba(255, 215, 0, 0.4);
}

.leaderboard-item.rank-2 {
    background: linear-gradient(90deg, rgba(192, 192, 192, 0.1) 0%, rgba(192, 192, 192, 0.03) 100%);
    border-color: rgba(192, 192, 192, 0.3);
}

.leaderboard-item.rank-3 {
    background: linear-gradient(90deg, rgba(205, 127, 50, 0.1) 0%, rgba(205, 127, 50, 0.03) 100%);
    border-color: rgba(205, 127, 50, 0.3);
}

.rank-badge {
    width: 6vh;
    height: 6vh;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 3vh;
    font-weight: 700;
    color: #fff;
    background: rgba(100, 52, 248, 0.3);
    border: 2px solid rgba(100, 52, 248, 0.5);
    margin-right: 2vw;
    flex-shrink: 0;
}

.rank-1 .rank-badge {
    background: rgba(255, 215, 0, 0.3);
    border-color: #ffd700;
    color: #ffd700;
}

.rank-2 .rank-badge {
    background: rgba(192, 192, 192, 0.3);
    border-color: #c0c0c0;
    color: #c0c0c0;
}

.rank-3 .rank-badge {
    background: rgba(205, 127, 50, 0.3);
    border-color: #cd7f32;
    color: #cd7f32;
}

.store-info {
    flex: 1;
    min-width: 0;
    overflow: hidden;
}

.store-name {
    font-size: 3vh;
    font-weight: 600;
    color: #ffffff;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.store-value {
    font-size: 4vh;
    font-weight: 700;
    color: #4ade80;
    flex-shrink: 0;
    padding-left: 2vw;
}

/* Footer - 6% of viewport height */
.leaderboard-footer {
    height: 6vh;
    display: flex;
    align-items: center;
    justify-content: center;
    border-top: 1px solid rgba(255, 255, 255, 0.1);
    margin-top: 1vh;
    flex-shrink: 0;
}

.update-label {
    font-size: 1.5vh;
    color: rgba(255, 255, 255, 0.4);
    text-transform: uppercase;
    letter-spacing: 0.1em;
}"""
        leaderboard.save()
    except ScreenDesign.DoesNotExist:
        pass

    # Update Company Sales Dashboard - truly responsive
    try:
        dashboard = ScreenDesign.objects.get(slug='company-sales-dashboard')
        dashboard.css_code = """/* Responsive Dashboard - fits any screen from 14" to 100" */
/* All sizing based on viewport to guarantee fit */

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

.dashboard-container {
    height: 100vh;
    width: 100vw;
    padding: 2vh 3vw;
    background: linear-gradient(180deg, #0f0f1a 0%, #1a1a2e 100%);
    overflow: hidden;
    display: flex;
    flex-direction: column;
}

/* Header - 15% of viewport height */
.dashboard-header {
    text-align: center;
    height: 15vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
    flex-shrink: 0;
}

.company-name {
    font-size: 6vh;
    font-weight: 800;
    margin: 0;
    background: linear-gradient(90deg, #00f0ff, #9B59FF);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    line-height: 1.2;
}

.dashboard-date {
    font-size: 2vh;
    color: rgba(255, 255, 255, 0.5);
    text-transform: uppercase;
    letter-spacing: 0.2em;
    margin-top: 1vh;
}

/* Metrics Grid - 30% of viewport height */
.metrics-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 1.5vw;
    height: 30vh;
    margin-bottom: 2vh;
    flex-shrink: 0;
}

.metric-card {
    background: rgba(255, 255, 255, 0.03);
    border: 1px solid rgba(255, 255, 255, 0.1);
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    padding: 1vh 1vw;
}

.metric-label {
    font-size: 1.8vh;
    color: rgba(255, 255, 255, 0.6);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1vh;
}

.metric-value {
    font-size: 5vh;
    font-weight: 700;
    color: #ffffff;
    line-height: 1.2;
}

.metric-value.primary {
    color: #00f0ff;
}

.metric-value.accent {
    color: #9B59FF;
}

.metric-sub {
    font-size: 1.5vh;
    color: rgba(255, 255, 255, 0.4);
    margin-top: 0.5vh;
}

/* Leaderboard Section - remaining space (~50vh) */
.leaderboard-section {
    background: rgba(255, 255, 255, 0.02);
    border: 1px solid rgba(255, 255, 255, 0.08);
    padding: 2vh 2vw;
    flex: 1;
    display: flex;
    flex-direction: column;
    min-height: 0;
    overflow: hidden;
}

.section-title {
    font-size: 2.5vh;
    font-weight: 600;
    color: #ffffff;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1.5vh;
    flex-shrink: 0;
}

.mini-leaderboard {
    display: flex;
    flex-direction: column;
    gap: 1vh;
    flex: 1;
    min-height: 0;
    overflow: hidden;
}

.mini-item {
    display: flex;
    align-items: center;
    padding: 0 2vw;
    background: rgba(0, 0, 0, 0.2);
    border-left: 3px solid #6434f8;
    flex: 1;
    min-height: 0;
}

.mini-item:first-child {
    border-left-color: #ffd700;
    background: rgba(255, 215, 0, 0.05);
}

.mini-rank {
    font-size: 2.5vh;
    font-weight: 700;
    color: #6434f8;
    width: 5vw;
    min-width: 40px;
    flex-shrink: 0;
}

.mini-item:first-child .mini-rank {
    color: #ffd700;
}

.mini-name {
    flex: 1;
    font-size: 2.5vh;
    color: #ffffff;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    min-width: 0;
}

.mini-value {
    font-size: 3vh;
    font-weight: 700;
    color: #4ade80;
    flex-shrink: 0;
    padding-left: 2vw;
}"""
        dashboard.save()
    except ScreenDesign.DoesNotExist:
        pass


def revert_responsive_scaling(apps, schema_editor):
    """Revert (no-op)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0012_update_sample_designs_responsive'),
    ]

    operations = [
        migrations.RunPython(fix_responsive_scaling, revert_responsive_scaling),
    ]
