# Generated by Django 4.2

from django.db import migrations

# Jump.ca Brand Colors
# Pantone 7546 C: #253746 (Dark Blue)
# Pantone 3268 C: #00A98E (Teal)
# Pantone 137 C: #FAA41A (Orange)
# Pantone 225 C: #E44398 (Pink)
# Gradient: 135deg, #FAA41A 5%, #E44398 15%, #253746 35%, #00A98E 80%

# Common CSS for all Jump.ca screens
JUMPCA_BASE_CSS = """/* Jump.ca Branded Screen - Responsive for all screen sizes */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

.screen-container {
    height: 100vh;
    width: 100vw;
    padding: 2vh 3vw;
    background: linear-gradient(135deg, #FAA41A 5%, #E44398 15%, #253746 35%, #00A98E 80%);
    overflow: hidden;
    display: flex;
    flex-direction: column;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

/* Header */
.screen-header {
    text-align: center;
    height: 12vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
    flex-shrink: 0;
}

.screen-title {
    font-size: 5vh;
    font-weight: 700;
    color: #ffffff;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    text-shadow: 0 2px 10px rgba(0,0,0,0.3);
}

.screen-subtitle {
    font-size: 2.5vh;
    color: rgba(255, 255, 255, 0.9);
    font-weight: 500;
    margin-top: 0.5vh;
}

/* Totals Section */
.totals-section {
    display: flex;
    justify-content: center;
    gap: 4vw;
    height: 12vh;
    margin: 1vh 0;
    flex-shrink: 0;
}

.total-card {
    background: rgba(255, 255, 255, 0.15);
    backdrop-filter: blur(10px);
    border: 1px solid rgba(255, 255, 255, 0.2);
    border-radius: 1vh;
    padding: 1.5vh 4vw;
    text-align: center;
    display: flex;
    flex-direction: column;
    justify-content: center;
}

.total-label {
    font-size: 2vh;
    color: rgba(255, 255, 255, 0.8);
    text-transform: uppercase;
    letter-spacing: 0.05em;
    margin-bottom: 0.5vh;
}

.total-value {
    font-size: 4.5vh;
    font-weight: 700;
    color: #ffffff;
    text-shadow: 0 2px 8px rgba(0,0,0,0.2);
}

/* Two Column Layout */
.two-column {
    flex: 1;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 2vw;
    min-height: 0;
    overflow: hidden;
}

/* Single Column Layout (for rankings) */
.single-column {
    flex: 1;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 2vw;
    min-height: 0;
    overflow: hidden;
}

/* Leaderboard Panel */
.leaderboard-panel {
    background: rgba(0, 0, 0, 0.25);
    backdrop-filter: blur(10px);
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-radius: 1vh;
    padding: 1.5vh 1.5vw;
    display: flex;
    flex-direction: column;
    overflow: hidden;
}

.panel-title {
    font-size: 2.2vh;
    font-weight: 600;
    color: #FAA41A;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    margin-bottom: 1vh;
    flex-shrink: 0;
    text-align: center;
}

.leaderboard-list {
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 0.8vh;
    overflow: hidden;
}

.leaderboard-item {
    display: flex;
    align-items: center;
    padding: 0 1.5vw;
    background: rgba(255, 255, 255, 0.08);
    border-radius: 0.5vh;
    flex: 1;
    min-height: 0;
}

.leaderboard-item.rank-1 {
    background: linear-gradient(90deg, rgba(250, 164, 26, 0.3) 0%, rgba(250, 164, 26, 0.1) 100%);
    border: 1px solid rgba(250, 164, 26, 0.4);
}

.leaderboard-item.rank-2 {
    background: linear-gradient(90deg, rgba(228, 67, 152, 0.2) 0%, rgba(228, 67, 152, 0.05) 100%);
    border: 1px solid rgba(228, 67, 152, 0.3);
}

.leaderboard-item.rank-3 {
    background: linear-gradient(90deg, rgba(0, 169, 142, 0.2) 0%, rgba(0, 169, 142, 0.05) 100%);
    border: 1px solid rgba(0, 169, 142, 0.3);
}

.rank-badge {
    width: 4vh;
    height: 4vh;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 2.2vh;
    font-weight: 700;
    color: #fff;
    background: rgba(37, 55, 70, 0.6);
    border-radius: 50%;
    margin-right: 1.5vw;
    flex-shrink: 0;
}

.rank-1 .rank-badge {
    background: #FAA41A;
    color: #253746;
}

.rank-2 .rank-badge {
    background: #E44398;
}

.rank-3 .rank-badge {
    background: #00A98E;
}

.store-name {
    flex: 1;
    font-size: 2.2vh;
    font-weight: 500;
    color: #ffffff;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.store-value {
    font-size: 2.8vh;
    font-weight: 700;
    color: #FAA41A;
    flex-shrink: 0;
    padding-left: 1vw;
}

/* Footer */
.screen-footer {
    height: 4vh;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
}

.footer-text {
    font-size: 1.5vh;
    color: rgba(255, 255, 255, 0.5);
}
"""


def create_jumpca_screens(apps, schema_editor):
    """Create 6 Jump.ca branded screens."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')

    # Screen 1: Today Summary with Top 5
    ScreenDesign.objects.create(
        name="Jump.ca - Today Summary",
        slug="jumpca-today-summary",
        description="Today's totals and Top 5 for both Devices and Profit",
        html_code="""<div class="screen-container">
    <div class="screen-header">
        <h1 class="screen-title">Today</h1>
    </div>

    <div class="totals-section">
        <div class="total-card">
            <span class="total-label">Total Devices</span>
            <span class="total-value">{{sales.today.totals.devices}}</span>
        </div>
        <div class="total-card">
            <span class="total-label">Total Profit</span>
            <span class="total-value">{{sales.today.totals.profit}}</span>
        </div>
    </div>

    <div class="two-column">
        <div class="leaderboard-panel">
            <h2 class="panel-title">Top 5 Locations - Devices</h2>
            <div class="leaderboard-list">
                {{#each sales.today.top5_devices}}
                <div class="leaderboard-item rank-{{rank}}">
                    <div class="rank-badge">{{rank}}</div>
                    <span class="store-name">{{store_name}}</span>
                    <span class="store-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>

        <div class="leaderboard-panel">
            <h2 class="panel-title">Top 5 Locations - Profit</h2>
            <div class="leaderboard-list">
                {{#each sales.today.top5_profit}}
                <div class="leaderboard-item rank-{{rank}}">
                    <div class="rank-badge">{{rank}}</div>
                    <span class="store-name">{{store_name}}</span>
                    <span class="store-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>
    </div>

    <div class="screen-footer">
        <span class="footer-text">Data refreshes every 5 minutes</span>
    </div>
</div>""",
        css_code=JUMPCA_BASE_CSS,
        js_code="",
        notes="Jump.ca branded - Today's summary with totals and top 5 for devices and profit",
        is_active=True,
    )

    # Screen 2: Today Full Rankings
    ScreenDesign.objects.create(
        name="Jump.ca - Today Rankings",
        slug="jumpca-today-rankings",
        description="Full ranking of all locations for Today - Devices and Profit",
        html_code="""<div class="screen-container">
    <div class="screen-header">
        <h1 class="screen-title">Today - All Locations</h1>
    </div>

    <div class="single-column">
        <div class="leaderboard-panel">
            <h2 class="panel-title">Devices Ranking</h2>
            <div class="leaderboard-list">
                {{#each sales.today.all_devices}}
                <div class="leaderboard-item rank-{{rank}}">
                    <div class="rank-badge">{{rank}}</div>
                    <span class="store-name">{{store_name}}</span>
                    <span class="store-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>

        <div class="leaderboard-panel">
            <h2 class="panel-title">Profit Ranking</h2>
            <div class="leaderboard-list">
                {{#each sales.today.all_profit}}
                <div class="leaderboard-item rank-{{rank}}">
                    <div class="rank-badge">{{rank}}</div>
                    <span class="store-name">{{store_name}}</span>
                    <span class="store-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>
    </div>

    <div class="screen-footer">
        <span class="footer-text">Data refreshes every 5 minutes</span>
    </div>
</div>""",
        css_code=JUMPCA_BASE_CSS,
        js_code="",
        notes="Jump.ca branded - Full rankings for today (all locations)",
        is_active=True,
    )

    # Screen 3: Week to Date Summary with Top 5
    ScreenDesign.objects.create(
        name="Jump.ca - Week to Date Summary",
        slug="jumpca-wtd-summary",
        description="Week to Date totals and Top 5 for both Devices and Profit",
        html_code="""<div class="screen-container">
    <div class="screen-header">
        <h1 class="screen-title">Week to Date</h1>
    </div>

    <div class="totals-section">
        <div class="total-card">
            <span class="total-label">Total Devices</span>
            <span class="total-value">{{sales.wtd.totals.devices}}</span>
        </div>
        <div class="total-card">
            <span class="total-label">Total Profit</span>
            <span class="total-value">{{sales.wtd.totals.profit}}</span>
        </div>
    </div>

    <div class="two-column">
        <div class="leaderboard-panel">
            <h2 class="panel-title">Top 5 Locations - Devices</h2>
            <div class="leaderboard-list">
                {{#each sales.wtd.top5_devices}}
                <div class="leaderboard-item rank-{{rank}}">
                    <div class="rank-badge">{{rank}}</div>
                    <span class="store-name">{{store_name}}</span>
                    <span class="store-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>

        <div class="leaderboard-panel">
            <h2 class="panel-title">Top 5 Locations - Profit</h2>
            <div class="leaderboard-list">
                {{#each sales.wtd.top5_profit}}
                <div class="leaderboard-item rank-{{rank}}">
                    <div class="rank-badge">{{rank}}</div>
                    <span class="store-name">{{store_name}}</span>
                    <span class="store-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>
    </div>

    <div class="screen-footer">
        <span class="footer-text">Data refreshes every 5 minutes</span>
    </div>
</div>""",
        css_code=JUMPCA_BASE_CSS,
        js_code="",
        notes="Jump.ca branded - Week to Date summary with totals and top 5",
        is_active=True,
    )

    # Screen 4: Week to Date Full Rankings
    ScreenDesign.objects.create(
        name="Jump.ca - Week to Date Rankings",
        slug="jumpca-wtd-rankings",
        description="Full ranking of all locations for Week to Date - Devices and Profit",
        html_code="""<div class="screen-container">
    <div class="screen-header">
        <h1 class="screen-title">Week to Date - All Locations</h1>
    </div>

    <div class="single-column">
        <div class="leaderboard-panel">
            <h2 class="panel-title">Devices Ranking</h2>
            <div class="leaderboard-list">
                {{#each sales.wtd.all_devices}}
                <div class="leaderboard-item rank-{{rank}}">
                    <div class="rank-badge">{{rank}}</div>
                    <span class="store-name">{{store_name}}</span>
                    <span class="store-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>

        <div class="leaderboard-panel">
            <h2 class="panel-title">Profit Ranking</h2>
            <div class="leaderboard-list">
                {{#each sales.wtd.all_profit}}
                <div class="leaderboard-item rank-{{rank}}">
                    <div class="rank-badge">{{rank}}</div>
                    <span class="store-name">{{store_name}}</span>
                    <span class="store-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>
    </div>

    <div class="screen-footer">
        <span class="footer-text">Data refreshes every 5 minutes</span>
    </div>
</div>""",
        css_code=JUMPCA_BASE_CSS,
        js_code="",
        notes="Jump.ca branded - Full rankings for week to date (all locations)",
        is_active=True,
    )

    # Screen 5: Month to Date Summary with Top 5
    ScreenDesign.objects.create(
        name="Jump.ca - Month to Date Summary",
        slug="jumpca-mtd-summary",
        description="Month to Date totals and Top 5 for both Devices and Profit",
        html_code="""<div class="screen-container">
    <div class="screen-header">
        <h1 class="screen-title">Month to Date</h1>
    </div>

    <div class="totals-section">
        <div class="total-card">
            <span class="total-label">Total Devices</span>
            <span class="total-value">{{sales.mtd.totals.devices}}</span>
        </div>
        <div class="total-card">
            <span class="total-label">Total Profit</span>
            <span class="total-value">{{sales.mtd.totals.profit}}</span>
        </div>
    </div>

    <div class="two-column">
        <div class="leaderboard-panel">
            <h2 class="panel-title">Top 5 Locations - Devices</h2>
            <div class="leaderboard-list">
                {{#each sales.mtd.top5_devices}}
                <div class="leaderboard-item rank-{{rank}}">
                    <div class="rank-badge">{{rank}}</div>
                    <span class="store-name">{{store_name}}</span>
                    <span class="store-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>

        <div class="leaderboard-panel">
            <h2 class="panel-title">Top 5 Locations - Profit</h2>
            <div class="leaderboard-list">
                {{#each sales.mtd.top5_profit}}
                <div class="leaderboard-item rank-{{rank}}">
                    <div class="rank-badge">{{rank}}</div>
                    <span class="store-name">{{store_name}}</span>
                    <span class="store-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>
    </div>

    <div class="screen-footer">
        <span class="footer-text">Data refreshes every 5 minutes</span>
    </div>
</div>""",
        css_code=JUMPCA_BASE_CSS,
        js_code="",
        notes="Jump.ca branded - Month to Date summary with totals and top 5",
        is_active=True,
    )

    # Screen 6: Month to Date Full Rankings
    ScreenDesign.objects.create(
        name="Jump.ca - Month to Date Rankings",
        slug="jumpca-mtd-rankings",
        description="Full ranking of all locations for Month to Date - Devices and Profit",
        html_code="""<div class="screen-container">
    <div class="screen-header">
        <h1 class="screen-title">Month to Date - All Locations</h1>
    </div>

    <div class="single-column">
        <div class="leaderboard-panel">
            <h2 class="panel-title">Devices Ranking</h2>
            <div class="leaderboard-list">
                {{#each sales.mtd.all_devices}}
                <div class="leaderboard-item rank-{{rank}}">
                    <div class="rank-badge">{{rank}}</div>
                    <span class="store-name">{{store_name}}</span>
                    <span class="store-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>

        <div class="leaderboard-panel">
            <h2 class="panel-title">Profit Ranking</h2>
            <div class="leaderboard-list">
                {{#each sales.mtd.all_profit}}
                <div class="leaderboard-item rank-{{rank}}">
                    <div class="rank-badge">{{rank}}</div>
                    <span class="store-name">{{store_name}}</span>
                    <span class="store-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>
    </div>

    <div class="screen-footer">
        <span class="footer-text">Data refreshes every 5 minutes</span>
    </div>
</div>""",
        css_code=JUMPCA_BASE_CSS,
        js_code="",
        notes="Jump.ca branded - Full rankings for month to date (all locations)",
        is_active=True,
    )


def remove_jumpca_screens(apps, schema_editor):
    """Remove Jump.ca branded screens."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')
    ScreenDesign.objects.filter(slug__in=[
        'jumpca-today-summary',
        'jumpca-today-rankings',
        'jumpca-wtd-summary',
        'jumpca-wtd-rankings',
        'jumpca-mtd-summary',
        'jumpca-mtd-rankings',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0013_fix_responsive_scaling'),
    ]

    operations = [
        migrations.RunPython(create_jumpca_screens, remove_jumpca_screens),
    ]
