# Generated by Django 4.2

from django.db import migrations

# Updated Jump.ca CSS with 315° gradient, square styling, white titles
JUMPCA_UPDATED_CSS = """/* Jump.ca Branded Screen - Square styling, 315° gradient */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

.screen-container {
    height: 100vh;
    width: 100vw;
    padding: 2vh 3vw;
    background: linear-gradient(315deg, #FAA41A 5%, #E44398 15%, #253746 35%, #00A98E 80%);
    overflow: hidden;
    display: flex;
    flex-direction: column;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

/* Header */
.screen-header {
    text-align: center;
    height: 12vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
    flex-shrink: 0;
}

.screen-title {
    font-size: 5vh;
    font-weight: 700;
    color: #ffffff;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    text-shadow: 0 2px 10px rgba(0,0,0,0.3);
}

.screen-subtitle {
    font-size: 2.5vh;
    color: rgba(255, 255, 255, 0.9);
    font-weight: 500;
    margin-top: 0.5vh;
}

/* Totals Section */
.totals-section {
    display: flex;
    justify-content: center;
    gap: 4vw;
    height: 12vh;
    margin: 1vh 0;
    flex-shrink: 0;
}

.total-card {
    background: rgba(255, 255, 255, 0.15);
    backdrop-filter: blur(10px);
    border: 1px solid rgba(255, 255, 255, 0.2);
    padding: 1.5vh 4vw;
    text-align: center;
    display: flex;
    flex-direction: column;
    justify-content: center;
}

.total-label {
    font-size: 2vh;
    color: rgba(255, 255, 255, 0.8);
    text-transform: uppercase;
    letter-spacing: 0.05em;
    margin-bottom: 0.5vh;
}

.total-value {
    font-size: 4.5vh;
    font-weight: 700;
    color: #ffffff;
    text-shadow: 0 2px 8px rgba(0,0,0,0.2);
}

/* Two Column Layout */
.two-column {
    flex: 1;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 2vw;
    min-height: 0;
    overflow: hidden;
}

/* Single Column Layout (for rankings) */
.single-column {
    flex: 1;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 2vw;
    min-height: 0;
    overflow: hidden;
}

/* Leaderboard Panel - Square styling */
.leaderboard-panel {
    background: rgba(0, 0, 0, 0.25);
    backdrop-filter: blur(10px);
    border: 1px solid rgba(255, 255, 255, 0.1);
    padding: 1.5vh 1.5vw;
    display: flex;
    flex-direction: column;
    overflow: hidden;
}

.panel-title {
    font-size: 2.2vh;
    font-weight: 600;
    color: #ffffff;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    margin-bottom: 1vh;
    flex-shrink: 0;
    text-align: center;
}

.leaderboard-list {
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 0.8vh;
    overflow: hidden;
}

.leaderboard-item {
    display: flex;
    align-items: center;
    padding: 0 1.5vw;
    background: rgba(255, 255, 255, 0.08);
    border: 1px solid rgba(255, 255, 255, 0.1);
    flex: 1;
    min-height: 0;
}

.leaderboard-item.rank-1 {
    background: linear-gradient(90deg, rgba(250, 164, 26, 0.3) 0%, rgba(250, 164, 26, 0.1) 100%);
    border-color: rgba(250, 164, 26, 0.4);
}

.leaderboard-item.rank-2 {
    background: linear-gradient(90deg, rgba(228, 67, 152, 0.2) 0%, rgba(228, 67, 152, 0.05) 100%);
    border-color: rgba(228, 67, 152, 0.3);
}

.leaderboard-item.rank-3 {
    background: linear-gradient(90deg, rgba(0, 169, 142, 0.2) 0%, rgba(0, 169, 142, 0.05) 100%);
    border-color: rgba(0, 169, 142, 0.3);
}

.rank-badge {
    width: 4vh;
    height: 4vh;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 2.2vh;
    font-weight: 700;
    color: #fff;
    background: rgba(37, 55, 70, 0.6);
    border: 2px solid rgba(37, 55, 70, 0.8);
    margin-right: 1.5vw;
    flex-shrink: 0;
}

.rank-1 .rank-badge {
    background: #FAA41A;
    border-color: #FAA41A;
    color: #253746;
}

.rank-2 .rank-badge {
    background: #E44398;
    border-color: #E44398;
}

.rank-3 .rank-badge {
    background: #00A98E;
    border-color: #00A98E;
}

.store-name {
    flex: 1;
    font-size: 2.2vh;
    font-weight: 500;
    color: #ffffff;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.store-value {
    font-size: 2.8vh;
    font-weight: 700;
    color: #FAA41A;
    flex-shrink: 0;
    padding-left: 1vw;
}

/* Footer */
.screen-footer {
    height: 4vh;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
}

.footer-text {
    font-size: 1.5vh;
    color: rgba(255, 255, 255, 0.5);
}
"""

# Company Dashboard CSS
COMPANY_DASHBOARD_CSS = """/* Jump.ca Company Dashboard - Square styling, 315° gradient */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

.dashboard-container {
    height: 100vh;
    width: 100vw;
    padding: 2vh 3vw;
    background: linear-gradient(315deg, #FAA41A 5%, #E44398 15%, #253746 35%, #00A98E 80%);
    overflow: hidden;
    display: flex;
    flex-direction: column;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

/* Header */
.dashboard-header {
    text-align: center;
    height: 15vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
    flex-shrink: 0;
}

.company-name {
    font-size: 6vh;
    font-weight: 800;
    margin: 0;
    color: #ffffff;
    text-shadow: 0 2px 15px rgba(0,0,0,0.3);
}

.dashboard-date {
    font-size: 2vh;
    color: rgba(255, 255, 255, 0.7);
    text-transform: uppercase;
    letter-spacing: 0.2em;
    margin-top: 1vh;
}

/* Metrics Grid */
.metrics-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 1.5vw;
    height: 30vh;
    margin-bottom: 2vh;
    flex-shrink: 0;
}

.metric-card {
    background: rgba(0, 0, 0, 0.25);
    border: 1px solid rgba(255, 255, 255, 0.1);
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    padding: 1vh 1vw;
}

.metric-label {
    font-size: 1.8vh;
    color: rgba(255, 255, 255, 0.7);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1vh;
}

.metric-value {
    font-size: 5vh;
    font-weight: 700;
    color: #ffffff;
    line-height: 1.2;
}

.metric-value.primary {
    color: #FAA41A;
}

.metric-value.accent {
    color: #00A98E;
}

.metric-sub {
    font-size: 1.5vh;
    color: rgba(255, 255, 255, 0.5);
    margin-top: 0.5vh;
}

/* Leaderboard Section */
.leaderboard-section {
    background: rgba(0, 0, 0, 0.2);
    border: 1px solid rgba(255, 255, 255, 0.1);
    padding: 2vh 2vw;
    flex: 1;
    display: flex;
    flex-direction: column;
    min-height: 0;
    overflow: hidden;
}

.section-title {
    font-size: 2.5vh;
    font-weight: 600;
    color: #ffffff;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1.5vh;
    flex-shrink: 0;
}

.mini-leaderboard {
    display: flex;
    flex-direction: column;
    gap: 1vh;
    flex: 1;
    min-height: 0;
    overflow: hidden;
}

.mini-item {
    display: flex;
    align-items: center;
    padding: 0 2vw;
    background: rgba(255, 255, 255, 0.05);
    border-left: 3px solid #E44398;
    flex: 1;
    min-height: 0;
}

.mini-item:first-child {
    border-left-color: #FAA41A;
    background: rgba(250, 164, 26, 0.1);
}

.mini-rank {
    font-size: 2.5vh;
    font-weight: 700;
    color: #E44398;
    width: 5vw;
    min-width: 40px;
    flex-shrink: 0;
}

.mini-item:first-child .mini-rank {
    color: #FAA41A;
}

.mini-name {
    flex: 1;
    font-size: 2.5vh;
    color: #ffffff;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    min-width: 0;
}

.mini-value {
    font-size: 3vh;
    font-weight: 700;
    color: #00A98E;
    flex-shrink: 0;
    padding-left: 2vw;
}
"""

# Top Performers CSS
TOP_PERFORMERS_CSS = """/* Jump.ca Top Performers - Square styling, 315° gradient */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

.leaderboard-container {
    display: flex;
    flex-direction: column;
    height: 100vh;
    width: 100vw;
    padding: 2vh 3vw;
    background: linear-gradient(315deg, #FAA41A 5%, #E44398 15%, #253746 35%, #00A98E 80%);
    overflow: hidden;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

/* Header */
.leaderboard-header {
    text-align: center;
    height: 12vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
    flex-shrink: 0;
}

.leaderboard-title {
    font-size: 4.5vh;
    font-weight: 700;
    color: #ffffff;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    text-shadow: 0 2px 10px rgba(0,0,0,0.3);
}

.leaderboard-subtitle {
    font-size: 2.5vh;
    color: rgba(255, 255, 255, 0.9);
    font-weight: 500;
    margin-top: 0.5vh;
}

/* Total Section */
.total-section {
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 3vw;
    height: 10vh;
    background: rgba(0, 0, 0, 0.2);
    border: 1px solid rgba(255, 255, 255, 0.1);
    margin: 1vh 0 2vh 0;
    flex-shrink: 0;
}

.total-label {
    font-size: 2vh;
    color: rgba(255, 255, 255, 0.7);
    text-transform: uppercase;
    letter-spacing: 0.05em;
}

.total-value {
    font-size: 5vh;
    font-weight: 700;
    color: #FAA41A;
}

/* Leaderboard List */
.leaderboard-list {
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 1vh;
    min-height: 0;
    overflow: hidden;
}

.leaderboard-item {
    display: flex;
    align-items: center;
    padding: 0 2vw;
    background: rgba(255, 255, 255, 0.08);
    border: 1px solid rgba(255, 255, 255, 0.1);
    flex: 1;
    min-height: 0;
}

/* Rank-specific styling */
.leaderboard-item.rank-1 {
    background: linear-gradient(90deg, rgba(250, 164, 26, 0.3) 0%, rgba(250, 164, 26, 0.1) 100%);
    border-color: rgba(250, 164, 26, 0.4);
}

.leaderboard-item.rank-2 {
    background: linear-gradient(90deg, rgba(228, 67, 152, 0.2) 0%, rgba(228, 67, 152, 0.05) 100%);
    border-color: rgba(228, 67, 152, 0.3);
}

.leaderboard-item.rank-3 {
    background: linear-gradient(90deg, rgba(0, 169, 142, 0.2) 0%, rgba(0, 169, 142, 0.05) 100%);
    border-color: rgba(0, 169, 142, 0.3);
}

.rank-badge {
    width: 6vh;
    height: 6vh;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 3vh;
    font-weight: 700;
    color: #fff;
    background: rgba(37, 55, 70, 0.6);
    border: 2px solid rgba(37, 55, 70, 0.8);
    margin-right: 2vw;
    flex-shrink: 0;
}

.rank-1 .rank-badge {
    background: #FAA41A;
    border-color: #FAA41A;
    color: #253746;
}

.rank-2 .rank-badge {
    background: #E44398;
    border-color: #E44398;
}

.rank-3 .rank-badge {
    background: #00A98E;
    border-color: #00A98E;
}

.store-info {
    flex: 1;
    min-width: 0;
    overflow: hidden;
}

.store-name {
    font-size: 3vh;
    font-weight: 600;
    color: #ffffff;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.store-value {
    font-size: 4vh;
    font-weight: 700;
    color: #00A98E;
    flex-shrink: 0;
    padding-left: 2vw;
}

/* Footer */
.leaderboard-footer {
    height: 6vh;
    display: flex;
    align-items: center;
    justify-content: center;
    border-top: 1px solid rgba(255, 255, 255, 0.1);
    margin-top: 1vh;
    flex-shrink: 0;
}

.update-label {
    font-size: 1.5vh;
    color: rgba(255, 255, 255, 0.4);
    text-transform: uppercase;
    letter-spacing: 0.1em;
}
"""


def update_jumpca_screens(apps, schema_editor):
    """Update Jump.ca screens with 315° gradient, square styling, white titles + add new screens."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')

    # Update all existing Jump.ca screens with new CSS
    jumpca_slugs = [
        'jumpca-today-summary',
        'jumpca-today-rankings',
        'jumpca-wtd-summary',
        'jumpca-wtd-rankings',
        'jumpca-mtd-summary',
        'jumpca-mtd-rankings',
    ]

    for slug in jumpca_slugs:
        try:
            screen = ScreenDesign.objects.get(slug=slug)
            screen.css_code = JUMPCA_UPDATED_CSS
            screen.save()
        except ScreenDesign.DoesNotExist:
            pass

    # Create new Company Dashboard screen
    ScreenDesign.objects.create(
        name="Jump.ca - Company Dashboard",
        slug="jumpca-company-dashboard",
        description="Company dashboard showing Today/WTD/MTD metrics with Top 5 leaderboard",
        html_code="""<div class="dashboard-container">
    <div class="dashboard-header">
        <h1 class="company-name">Jump.ca Sales</h1>
        <p class="dashboard-date">Live Performance</p>
    </div>

    <div class="metrics-grid">
        <div class="metric-card">
            <div class="metric-label">Today's Profit</div>
            <div class="metric-value primary">{{sales.today.totals.profit}}</div>
            <div class="metric-sub">{{sales.today.totals.invoice_count}} invoices</div>
        </div>

        <div class="metric-card">
            <div class="metric-label">Week to Date</div>
            <div class="metric-value">{{sales.wtd.totals.profit}}</div>
            <div class="metric-sub">{{sales.wtd.totals.devices}} devices</div>
        </div>

        <div class="metric-card">
            <div class="metric-label">Month to Date</div>
            <div class="metric-value">{{sales.mtd.totals.profit}}</div>
            <div class="metric-sub">{{sales.mtd.totals.devices}} devices</div>
        </div>

        <div class="metric-card">
            <div class="metric-label">Today's Devices</div>
            <div class="metric-value accent">{{sales.today.totals.devices}}</div>
            <div class="metric-sub">units sold</div>
        </div>
    </div>

    <div class="leaderboard-section">
        <h2 class="section-title">Top 5 Today</h2>
        <div class="mini-leaderboard">
            {{#each sales.today.top5_profit}}
            <div class="mini-item">
                <span class="mini-rank">#{{rank}}</span>
                <span class="mini-name">{{store_name}}</span>
                <span class="mini-value">{{value}}</span>
            </div>
            {{/each}}
        </div>
    </div>
</div>""",
        css_code=COMPANY_DASHBOARD_CSS,
        js_code="",
        notes="Jump.ca branded company dashboard with metrics grid and top 5",
        is_active=True,
    )

    # Create Top Performers - Profit screen
    ScreenDesign.objects.create(
        name="Jump.ca - Top Performers Profit",
        slug="jumpca-top-performers-profit",
        description="Today's Top 5 Performers ranked by Profit",
        html_code="""<div class="leaderboard-container">
    <div class="leaderboard-header">
        <h1 class="leaderboard-title">Today's Top Performers</h1>
        <p class="leaderboard-subtitle">Profit Leaderboard</p>
    </div>

    <div class="total-section">
        <span class="total-label">Total Profit</span>
        <span class="total-value">{{sales.today.totals.profit}}</span>
    </div>

    <div class="leaderboard-list">
        {{#each sales.today.top5_profit}}
        <div class="leaderboard-item rank-{{rank}}">
            <div class="rank-badge">{{rank}}</div>
            <div class="store-info">
                <span class="store-name">{{store_name}}</span>
            </div>
            <div class="store-value">{{value}}</div>
        </div>
        {{/each}}
    </div>

    <div class="leaderboard-footer">
        <span class="update-label">Data refreshes every 5 minutes</span>
    </div>
</div>""",
        css_code=TOP_PERFORMERS_CSS,
        js_code="",
        notes="Jump.ca branded Top 5 Profit leaderboard",
        is_active=True,
    )

    # Create Top Performers - Devices screen
    ScreenDesign.objects.create(
        name="Jump.ca - Top Performers Devices",
        slug="jumpca-top-performers-devices",
        description="Today's Top 5 Performers ranked by Devices Sold",
        html_code="""<div class="leaderboard-container">
    <div class="leaderboard-header">
        <h1 class="leaderboard-title">Today's Top Performers</h1>
        <p class="leaderboard-subtitle">Devices Leaderboard</p>
    </div>

    <div class="total-section">
        <span class="total-label">Total Devices</span>
        <span class="total-value">{{sales.today.totals.devices}}</span>
    </div>

    <div class="leaderboard-list">
        {{#each sales.today.top5_devices}}
        <div class="leaderboard-item rank-{{rank}}">
            <div class="rank-badge">{{rank}}</div>
            <div class="store-info">
                <span class="store-name">{{store_name}}</span>
            </div>
            <div class="store-value">{{value}}</div>
        </div>
        {{/each}}
    </div>

    <div class="leaderboard-footer">
        <span class="update-label">Data refreshes every 5 minutes</span>
    </div>
</div>""",
        css_code=TOP_PERFORMERS_CSS,
        js_code="",
        notes="Jump.ca branded Top 5 Devices leaderboard",
        is_active=True,
    )


def remove_new_screens(apps, schema_editor):
    """Remove the new screens."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')
    ScreenDesign.objects.filter(slug__in=[
        'jumpca-company-dashboard',
        'jumpca-top-performers-profit',
        'jumpca-top-performers-devices',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0014_add_jumpca_branded_screens'),
    ]

    operations = [
        migrations.RunPython(update_jumpca_screens, remove_new_screens),
    ]
