# Generated by Django 4.2

from django.db import migrations

# Updated Company Dashboard CSS with side-by-side leaderboards and bigger sub labels
COMPANY_DASHBOARD_CSS_V2 = """/* Jump.ca Company Dashboard V2 - Side-by-side leaderboards */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

.dashboard-container {
    height: 100vh;
    width: 100vw;
    padding: 2vh 3vw;
    background: linear-gradient(315deg, #FAA41A 5%, #E44398 15%, #253746 35%, #00A98E 80%);
    overflow: hidden;
    display: flex;
    flex-direction: column;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

/* Header */
.dashboard-header {
    text-align: center;
    height: 12vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
    flex-shrink: 0;
}

.company-name {
    font-size: 6vh;
    font-weight: 800;
    margin: 0;
    color: #ffffff;
    text-shadow: 0 2px 15px rgba(0,0,0,0.3);
}

.dashboard-date {
    font-size: 2vh;
    color: rgba(255, 255, 255, 0.7);
    text-transform: uppercase;
    letter-spacing: 0.2em;
    margin-top: 1vh;
}

/* Metrics Grid */
.metrics-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 1.5vw;
    height: 25vh;
    margin-bottom: 2vh;
    flex-shrink: 0;
}

.metric-card {
    background: rgba(0, 0, 0, 0.25);
    border: 1px solid rgba(255, 255, 255, 0.1);
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    padding: 1vh 1vw;
}

.metric-label {
    font-size: 1.8vh;
    color: rgba(255, 255, 255, 0.7);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1vh;
}

.metric-value {
    font-size: 5vh;
    font-weight: 700;
    color: #ffffff;
    line-height: 1.2;
}

.metric-value.accent {
    color: #00A98E;
}

.metric-sub {
    font-size: 2vh;
    color: rgba(255, 255, 255, 0.6);
    margin-top: 0.5vh;
}

/* Two-Column Leaderboard Section */
.leaderboard-row {
    flex: 1;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 2vw;
    min-height: 0;
    overflow: hidden;
}

.leaderboard-section {
    background: rgba(0, 0, 0, 0.2);
    border: 1px solid rgba(255, 255, 255, 0.1);
    padding: 1.5vh 1.5vw;
    display: flex;
    flex-direction: column;
    min-height: 0;
    overflow: hidden;
}

.section-title {
    font-size: 2.2vh;
    font-weight: 600;
    color: #ffffff;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1vh;
    flex-shrink: 0;
    text-align: center;
}

.mini-leaderboard {
    display: flex;
    flex-direction: column;
    gap: 0.8vh;
    flex: 1;
    min-height: 0;
    overflow: hidden;
}

.mini-item {
    display: flex;
    align-items: center;
    padding: 0 1.5vw;
    background: rgba(255, 255, 255, 0.05);
    border-left: 3px solid #E44398;
    flex: 1;
    min-height: 0;
}

.mini-item:first-child {
    border-left-color: #FAA41A;
    background: rgba(250, 164, 26, 0.1);
}

.mini-rank {
    font-size: 2.2vh;
    font-weight: 700;
    color: #E44398;
    width: 4vw;
    min-width: 35px;
    flex-shrink: 0;
}

.mini-item:first-child .mini-rank {
    color: #FAA41A;
}

.mini-name {
    flex: 1;
    font-size: 2.2vh;
    color: #ffffff;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    min-width: 0;
}

.mini-value {
    font-size: 2.5vh;
    font-weight: 700;
    color: #00A98E;
    flex-shrink: 0;
    padding-left: 1vw;
}
"""

# Updated HTML with side-by-side Top 5 Profit and Top 5 Devices
COMPANY_DASHBOARD_HTML_V2 = """<div class="dashboard-container">
    <div class="dashboard-header">
        <h1 class="company-name">Jump.ca Sales</h1>
        <p class="dashboard-date">Live Performance</p>
    </div>

    <div class="metrics-grid">
        <div class="metric-card">
            <div class="metric-label">Today's Profit</div>
            <div class="metric-value accent">{{sales.today.totals.profit}}</div>
            <div class="metric-sub">{{sales.today.totals.invoice_count}} invoices</div>
        </div>

        <div class="metric-card">
            <div class="metric-label">Week to Date</div>
            <div class="metric-value">{{sales.wtd.totals.profit}}</div>
            <div class="metric-sub">{{sales.wtd.totals.devices}} devices</div>
        </div>

        <div class="metric-card">
            <div class="metric-label">Month to Date</div>
            <div class="metric-value">{{sales.mtd.totals.profit}}</div>
            <div class="metric-sub">{{sales.mtd.totals.devices}} devices</div>
        </div>

        <div class="metric-card">
            <div class="metric-label">Today's Devices</div>
            <div class="metric-value accent">{{sales.today.totals.devices}}</div>
            <div class="metric-sub">phones sold</div>
        </div>
    </div>

    <div class="leaderboard-row">
        <div class="leaderboard-section">
            <h2 class="section-title">Top 5 Profit Today</h2>
            <div class="mini-leaderboard">
                {{#each sales.today.top5_profit}}
                <div class="mini-item">
                    <span class="mini-rank">#{{rank}}</span>
                    <span class="mini-name">{{store_name}}</span>
                    <span class="mini-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>

        <div class="leaderboard-section">
            <h2 class="section-title">Top 5 Devices Today</h2>
            <div class="mini-leaderboard">
                {{#each sales.today.top5_devices}}
                <div class="mini-item">
                    <span class="mini-rank">#{{rank}}</span>
                    <span class="mini-name">{{store_name}}</span>
                    <span class="mini-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>
    </div>
</div>"""


def update_company_dashboard(apps, schema_editor):
    """Update Company Dashboard with side-by-side leaderboards and styling fixes."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')

    try:
        dashboard = ScreenDesign.objects.get(slug='jumpca-company-dashboard')
        dashboard.html_code = COMPANY_DASHBOARD_HTML_V2
        dashboard.css_code = COMPANY_DASHBOARD_CSS_V2
        dashboard.save()
    except ScreenDesign.DoesNotExist:
        pass


def revert_company_dashboard(apps, schema_editor):
    """Revert (no-op)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0015_update_jumpca_screens'),
    ]

    operations = [
        migrations.RunPython(update_company_dashboard, revert_company_dashboard),
    ]
