# Generated by Django 4.2

from django.db import migrations

# Updated Company Dashboard CSS with better header spacing and white leaderboard values
COMPANY_DASHBOARD_CSS_V3 = """/* Jump.ca Company Dashboard V3 - Better spacing, white values */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

.dashboard-container {
    height: 100vh;
    width: 100vw;
    padding: 2vh 3vw;
    background: linear-gradient(315deg, #FAA41A 5%, #E44398 15%, #253746 35%, #00A98E 80%);
    overflow: hidden;
    display: flex;
    flex-direction: column;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

/* Header - shifted up with less bottom space */
.dashboard-header {
    text-align: center;
    height: 10vh;
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    padding-top: 1vh;
    flex-shrink: 0;
}

.company-name {
    font-size: 6vh;
    font-weight: 800;
    margin: 0;
    color: #ffffff;
    text-shadow: 0 2px 15px rgba(0,0,0,0.3);
    line-height: 1;
}

.dashboard-date {
    font-size: 2vh;
    color: rgba(255, 255, 255, 0.7);
    text-transform: uppercase;
    letter-spacing: 0.2em;
    margin-top: 0.5vh;
}

/* Metrics Grid - more top margin for spacing from header */
.metrics-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 1.5vw;
    height: 25vh;
    margin-top: 2vh;
    margin-bottom: 2vh;
    flex-shrink: 0;
}

.metric-card {
    background: rgba(0, 0, 0, 0.25);
    border: 1px solid rgba(255, 255, 255, 0.1);
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    padding: 1vh 1vw;
}

.metric-label {
    font-size: 1.8vh;
    color: rgba(255, 255, 255, 0.7);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1vh;
}

.metric-value {
    font-size: 5vh;
    font-weight: 700;
    color: #ffffff;
    line-height: 1.2;
}

.metric-value.accent {
    color: #00A98E;
}

.metric-sub {
    font-size: 2vh;
    color: rgba(255, 255, 255, 0.6);
    margin-top: 0.5vh;
}

/* Two-Column Leaderboard Section */
.leaderboard-row {
    flex: 1;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 2vw;
    min-height: 0;
    overflow: hidden;
}

.leaderboard-section {
    background: rgba(0, 0, 0, 0.2);
    border: 1px solid rgba(255, 255, 255, 0.1);
    padding: 1.5vh 1.5vw;
    display: flex;
    flex-direction: column;
    min-height: 0;
    overflow: hidden;
}

.section-title {
    font-size: 2.2vh;
    font-weight: 600;
    color: #ffffff;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1vh;
    flex-shrink: 0;
    text-align: center;
}

.mini-leaderboard {
    display: flex;
    flex-direction: column;
    gap: 0.8vh;
    flex: 1;
    min-height: 0;
    overflow: hidden;
}

.mini-item {
    display: flex;
    align-items: center;
    padding: 0 1.5vw;
    background: rgba(255, 255, 255, 0.05);
    border-left: 3px solid #E44398;
    flex: 1;
    min-height: 0;
}

.mini-item:first-child {
    border-left-color: #FAA41A;
    background: rgba(250, 164, 26, 0.1);
}

.mini-rank {
    font-size: 2.2vh;
    font-weight: 700;
    color: #E44398;
    width: 4vw;
    min-width: 35px;
    flex-shrink: 0;
}

.mini-item:first-child .mini-rank {
    color: #FAA41A;
}

.mini-name {
    flex: 1;
    font-size: 2.2vh;
    color: #ffffff;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    min-width: 0;
}

.mini-value {
    font-size: 2.5vh;
    font-weight: 700;
    color: #ffffff;
    flex-shrink: 0;
    padding-left: 1vw;
}
"""


def update_dashboard_spacing(apps, schema_editor):
    """Update Company Dashboard with better spacing and white leaderboard values."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')

    try:
        dashboard = ScreenDesign.objects.get(slug='jumpca-company-dashboard')
        dashboard.css_code = COMPANY_DASHBOARD_CSS_V3
        dashboard.save()
    except ScreenDesign.DoesNotExist:
        pass


def revert_dashboard_spacing(apps, schema_editor):
    """Revert (no-op)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0016_update_company_dashboard'),
    ]

    operations = [
        migrations.RunPython(update_dashboard_spacing, revert_dashboard_spacing),
    ]
