# Generated by Django 4.2

from django.db import migrations

# Updated Company Dashboard CSS with gold/silver/bronze ranks
COMPANY_DASHBOARD_CSS_V4 = """/* Jump.ca Company Dashboard V4 - Gold/Silver/Bronze ranks */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

.dashboard-container {
    height: 100vh;
    width: 100vw;
    padding: 2vh 3vw;
    background: linear-gradient(315deg, #FAA41A 5%, #E44398 15%, #253746 35%, #00A98E 80%);
    overflow: hidden;
    display: flex;
    flex-direction: column;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

/* Header - shifted up with less bottom space */
.dashboard-header {
    text-align: center;
    height: 10vh;
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    padding-top: 1vh;
    flex-shrink: 0;
}

.company-name {
    font-size: 6vh;
    font-weight: 800;
    margin: 0;
    color: #ffffff;
    text-shadow: 0 2px 15px rgba(0,0,0,0.3);
    line-height: 1;
}

.dashboard-date {
    font-size: 2vh;
    color: rgba(255, 255, 255, 0.7);
    text-transform: uppercase;
    letter-spacing: 0.2em;
    margin-top: 0.5vh;
}

/* Metrics Grid - more top margin for spacing from header */
.metrics-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 1.5vw;
    height: 25vh;
    margin-top: 2vh;
    margin-bottom: 2vh;
    flex-shrink: 0;
}

.metric-card {
    background: rgba(0, 0, 0, 0.25);
    border: 1px solid rgba(255, 255, 255, 0.1);
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    padding: 1vh 1vw;
}

.metric-label {
    font-size: 1.8vh;
    color: rgba(255, 255, 255, 0.7);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1vh;
}

.metric-value {
    font-size: 5vh;
    font-weight: 700;
    color: #ffffff;
    line-height: 1.2;
}

.metric-value.primary {
    color: #FAA41A;
}

.metric-value.accent {
    color: #00A98E;
}

.metric-sub {
    font-size: 2vh;
    color: rgba(255, 255, 255, 0.6);
    margin-top: 0.5vh;
}

/* Two-Column Leaderboard Section */
.leaderboard-row {
    flex: 1;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 2vw;
    min-height: 0;
    overflow: hidden;
}

.leaderboard-section {
    background: rgba(0, 0, 0, 0.2);
    border: 1px solid rgba(255, 255, 255, 0.1);
    padding: 1.5vh 1.5vw;
    display: flex;
    flex-direction: column;
    min-height: 0;
    overflow: hidden;
}

.section-title {
    font-size: 2.2vh;
    font-weight: 600;
    color: #ffffff;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1vh;
    flex-shrink: 0;
    text-align: center;
}

.mini-leaderboard {
    display: flex;
    flex-direction: column;
    gap: 0.8vh;
    flex: 1;
    min-height: 0;
    overflow: hidden;
}

.mini-item {
    display: flex;
    align-items: center;
    padding: 0 1.5vw;
    background: rgba(255, 255, 255, 0.05);
    border-left: 3px solid rgba(255, 255, 255, 0.5);
    flex: 1;
    min-height: 0;
}

/* Rank 1 - Gold */
.mini-item:nth-child(1) {
    border-left-color: #FFD700;
    background: rgba(255, 215, 0, 0.1);
}

.mini-item:nth-child(1) .mini-rank {
    color: #FFD700;
}

/* Rank 2 - Silver */
.mini-item:nth-child(2) {
    border-left-color: #C0C0C0;
    background: rgba(192, 192, 192, 0.08);
}

.mini-item:nth-child(2) .mini-rank {
    color: #C0C0C0;
}

/* Rank 3 - Bronze */
.mini-item:nth-child(3) {
    border-left-color: #CD7F32;
    background: rgba(205, 127, 50, 0.08);
}

.mini-item:nth-child(3) .mini-rank {
    color: #CD7F32;
}

/* Rank 4 & 5 - White */
.mini-item:nth-child(4),
.mini-item:nth-child(5) {
    border-left-color: rgba(255, 255, 255, 0.5);
    background: rgba(255, 255, 255, 0.03);
}

.mini-item:nth-child(4) .mini-rank,
.mini-item:nth-child(5) .mini-rank {
    color: rgba(255, 255, 255, 0.7);
}

.mini-rank {
    font-size: 2.2vh;
    font-weight: 700;
    width: 4vw;
    min-width: 35px;
    flex-shrink: 0;
}

.mini-name {
    flex: 1;
    font-size: 2.2vh;
    color: #ffffff;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    min-width: 0;
}

.mini-value {
    font-size: 2.5vh;
    font-weight: 700;
    color: #ffffff;
    flex-shrink: 0;
    padding-left: 1vw;
}
"""

# Updated HTML - change Today's Profit to use primary (gold) class
COMPANY_DASHBOARD_HTML_V3 = """<div class="dashboard-container">
    <div class="dashboard-header">
        <h1 class="company-name">Jump.ca Sales</h1>
        <p class="dashboard-date">Live Performance</p>
    </div>

    <div class="metrics-grid">
        <div class="metric-card">
            <div class="metric-label">Today's Profit</div>
            <div class="metric-value primary">{{sales.today.totals.profit}}</div>
            <div class="metric-sub">{{sales.today.totals.invoice_count}} invoices</div>
        </div>

        <div class="metric-card">
            <div class="metric-label">Week to Date</div>
            <div class="metric-value">{{sales.wtd.totals.profit}}</div>
            <div class="metric-sub">{{sales.wtd.totals.devices}} devices</div>
        </div>

        <div class="metric-card">
            <div class="metric-label">Month to Date</div>
            <div class="metric-value">{{sales.mtd.totals.profit}}</div>
            <div class="metric-sub">{{sales.mtd.totals.devices}} devices</div>
        </div>

        <div class="metric-card">
            <div class="metric-label">Today's Devices</div>
            <div class="metric-value accent">{{sales.today.totals.devices}}</div>
            <div class="metric-sub">phones sold</div>
        </div>
    </div>

    <div class="leaderboard-row">
        <div class="leaderboard-section">
            <h2 class="section-title">Top 5 Profit Today</h2>
            <div class="mini-leaderboard">
                {{#each sales.today.top5_profit}}
                <div class="mini-item">
                    <span class="mini-rank">#{{rank}}</span>
                    <span class="mini-name">{{store_name}}</span>
                    <span class="mini-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>

        <div class="leaderboard-section">
            <h2 class="section-title">Top 5 Devices Today</h2>
            <div class="mini-leaderboard">
                {{#each sales.today.top5_devices}}
                <div class="mini-item">
                    <span class="mini-rank">#{{rank}}</span>
                    <span class="mini-name">{{store_name}}</span>
                    <span class="mini-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>
    </div>
</div>"""


def update_dashboard_rank_colors(apps, schema_editor):
    """Update Company Dashboard with gold/silver/bronze ranks and gold profit value."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')

    try:
        dashboard = ScreenDesign.objects.get(slug='jumpca-company-dashboard')
        dashboard.css_code = COMPANY_DASHBOARD_CSS_V4
        dashboard.html_code = COMPANY_DASHBOARD_HTML_V3
        dashboard.save()
    except ScreenDesign.DoesNotExist:
        pass


def revert_dashboard_rank_colors(apps, schema_editor):
    """Revert (no-op)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0017_dashboard_spacing_fix'),
    ]

    operations = [
        migrations.RunPython(update_dashboard_rank_colors, revert_dashboard_rank_colors),
    ]
