# Generated by Django 4.2

from django.db import migrations

# Updated Company Dashboard CSS with badge-style ranks like Top Performers
COMPANY_DASHBOARD_CSS_V6 = """/* Jump.ca Company Dashboard V6 - Badge-style ranks */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

.dashboard-container {
    height: 100vh;
    width: 100vw;
    padding: 2vh 3vw;
    background: linear-gradient(315deg, #FAA41A 5%, #E44398 15%, #253746 35%, #00A98E 80%);
    overflow: hidden;
    display: flex;
    flex-direction: column;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

/* Header - shifted up with less bottom space */
.dashboard-header {
    text-align: center;
    height: 10vh;
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    padding-top: 1vh;
    flex-shrink: 0;
}

.company-name {
    font-size: 6vh;
    font-weight: 800;
    margin: 0;
    color: #ffffff;
    text-shadow: 0 2px 15px rgba(0,0,0,0.3);
    line-height: 1;
}

.dashboard-date {
    font-size: 2vh;
    color: rgba(255, 255, 255, 0.7);
    text-transform: uppercase;
    letter-spacing: 0.2em;
    margin-top: 0.5vh;
}

/* Metrics Grid - more top margin for spacing from header */
.metrics-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 1.5vw;
    height: 25vh;
    margin-top: 2vh;
    margin-bottom: 2vh;
    flex-shrink: 0;
}

.metric-card {
    background: rgba(0, 0, 0, 0.25);
    border: 1px solid rgba(255, 255, 255, 0.1);
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    padding: 1vh 1vw;
}

.metric-label {
    font-size: 1.8vh;
    color: rgba(255, 255, 255, 0.7);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1vh;
}

.metric-value {
    font-size: 5vh;
    font-weight: 700;
    color: #ffffff;
    line-height: 1.2;
}

.metric-value.pink {
    color: #E44398;
}

.metric-value.accent {
    color: #00A98E;
}

.metric-sub {
    font-size: 2vh;
    color: rgba(255, 255, 255, 0.6);
    margin-top: 0.5vh;
}

/* Two-Column Leaderboard Section */
.leaderboard-row {
    flex: 1;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 2vw;
    min-height: 0;
    overflow: hidden;
}

.leaderboard-section {
    background: rgba(0, 0, 0, 0.2);
    border: 1px solid rgba(255, 255, 255, 0.1);
    padding: 1.5vh 1.5vw;
    display: flex;
    flex-direction: column;
    min-height: 0;
    overflow: hidden;
}

.section-title {
    font-size: 2.2vh;
    font-weight: 600;
    color: #ffffff;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1vh;
    flex-shrink: 0;
    text-align: center;
}

.mini-leaderboard {
    display: flex;
    flex-direction: column;
    gap: 0.8vh;
    flex: 1;
    min-height: 0;
    overflow: hidden;
}

.mini-item {
    display: flex;
    align-items: center;
    padding: 0 1.5vw;
    background: rgba(255, 255, 255, 0.05);
    flex: 1;
    min-height: 0;
}

/* Rank Badge - square box style */
.rank-badge {
    width: 4vh;
    height: 4vh;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 2.2vh;
    font-weight: 700;
    color: #fff;
    background: rgba(37, 55, 70, 0.6);
    border: 2px solid rgba(37, 55, 70, 0.8);
    margin-right: 1.5vw;
    flex-shrink: 0;
}

/* Rank 1 - Gold */
.mini-item:nth-child(1) .rank-badge {
    background: #FFD700;
    border-color: #FFD700;
    color: #253746;
}

/* Rank 2 - Silver */
.mini-item:nth-child(2) .rank-badge {
    background: #C0C0C0;
    border-color: #C0C0C0;
    color: #253746;
}

/* Rank 3 - Bronze */
.mini-item:nth-child(3) .rank-badge {
    background: #CD7F32;
    border-color: #CD7F32;
    color: #fff;
}

/* Rank 4 & 5 - White/Light */
.mini-item:nth-child(4) .rank-badge,
.mini-item:nth-child(5) .rank-badge {
    background: rgba(255, 255, 255, 0.3);
    border-color: rgba(255, 255, 255, 0.5);
    color: #fff;
}

.mini-name {
    flex: 1;
    font-size: 2.2vh;
    color: #ffffff;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    min-width: 0;
}

.mini-value {
    font-size: 2.5vh;
    font-weight: 700;
    color: #ffffff;
    flex-shrink: 0;
    padding-left: 1vw;
}
"""

# Updated HTML - use rank-badge instead of #rank text
COMPANY_DASHBOARD_HTML_V5 = """<div class="dashboard-container">
    <div class="dashboard-header">
        <h1 class="company-name">Jump.ca Sales</h1>
        <p class="dashboard-date">Live Performance</p>
    </div>

    <div class="metrics-grid">
        <div class="metric-card">
            <div class="metric-label">Today's Profit</div>
            <div class="metric-value pink">{{sales.today.totals.profit}}</div>
            <div class="metric-sub">{{sales.today.totals.invoice_count}} invoices</div>
        </div>

        <div class="metric-card">
            <div class="metric-label">Week to Date</div>
            <div class="metric-value">{{sales.wtd.totals.profit}}</div>
            <div class="metric-sub">{{sales.wtd.totals.devices}} devices</div>
        </div>

        <div class="metric-card">
            <div class="metric-label">Month to Date</div>
            <div class="metric-value">{{sales.mtd.totals.profit}}</div>
            <div class="metric-sub">{{sales.mtd.totals.devices}} devices</div>
        </div>

        <div class="metric-card">
            <div class="metric-label">Today's Devices</div>
            <div class="metric-value accent">{{sales.today.totals.devices}}</div>
            <div class="metric-sub">phones sold</div>
        </div>
    </div>

    <div class="leaderboard-row">
        <div class="leaderboard-section">
            <h2 class="section-title">Top 5 Profit Today</h2>
            <div class="mini-leaderboard">
                {{#each sales.today.top5_profit}}
                <div class="mini-item">
                    <div class="rank-badge">{{rank}}</div>
                    <span class="mini-name">{{store_name}}</span>
                    <span class="mini-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>

        <div class="leaderboard-section">
            <h2 class="section-title">Top 5 Devices Today</h2>
            <div class="mini-leaderboard">
                {{#each sales.today.top5_devices}}
                <div class="mini-item">
                    <div class="rank-badge">{{rank}}</div>
                    <span class="mini-name">{{store_name}}</span>
                    <span class="mini-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>
    </div>
</div>"""


def update_dashboard_badge_style(apps, schema_editor):
    """Update Company Dashboard with badge-style ranks like Top Performers."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')

    try:
        dashboard = ScreenDesign.objects.get(slug='jumpca-company-dashboard')
        dashboard.css_code = COMPANY_DASHBOARD_CSS_V6
        dashboard.html_code = COMPANY_DASHBOARD_HTML_V5
        dashboard.save()
    except ScreenDesign.DoesNotExist:
        pass


def revert_dashboard_badge_style(apps, schema_editor):
    """Revert (no-op)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0019_dashboard_profit_pink'),
    ]

    operations = [
        migrations.RunPython(update_dashboard_badge_style, revert_dashboard_badge_style),
    ]
