# Generated by Django 4.2

from django.db import migrations


def update_rankings_to_top15(apps, schema_editor):
    """Update ranking screens to show top 15 instead of top 20."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')

    # Update Today Rankings
    try:
        screen = ScreenDesign.objects.get(slug='jumpca-today-rankings')
        screen.name = "Jump.ca - Today Top 15"
        screen.description = "Top 15 locations for Today - Devices and Profit"
        screen.html_code = """<div class="screen-container">
    <div class="screen-header">
        <h1 class="screen-title">Today - Top 15</h1>
    </div>

    <div class="single-column">
        <div class="leaderboard-panel">
            <h2 class="panel-title">Devices Ranking</h2>
            <div class="leaderboard-list">
                {{#each sales.today.top15_devices}}
                <div class="leaderboard-item rank-{{rank}}">
                    <div class="rank-badge">{{rank}}</div>
                    <span class="store-name">{{store_name}}</span>
                    <span class="store-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>

        <div class="leaderboard-panel">
            <h2 class="panel-title">Profit Ranking</h2>
            <div class="leaderboard-list">
                {{#each sales.today.top15_profit}}
                <div class="leaderboard-item rank-{{rank}}">
                    <div class="rank-badge">{{rank}}</div>
                    <span class="store-name">{{store_name}}</span>
                    <span class="store-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>
    </div>

    <div class="screen-footer">
        <span class="footer-text">Data refreshes every 5 minutes</span>
    </div>
</div>"""
        screen.save()
    except ScreenDesign.DoesNotExist:
        pass

    # Update WTD Rankings
    try:
        screen = ScreenDesign.objects.get(slug='jumpca-wtd-rankings')
        screen.name = "Jump.ca - Week to Date Top 15"
        screen.description = "Top 15 locations for Week to Date - Devices and Profit"
        screen.html_code = """<div class="screen-container">
    <div class="screen-header">
        <h1 class="screen-title">Week to Date - Top 15</h1>
    </div>

    <div class="single-column">
        <div class="leaderboard-panel">
            <h2 class="panel-title">Devices Ranking</h2>
            <div class="leaderboard-list">
                {{#each sales.wtd.top15_devices}}
                <div class="leaderboard-item rank-{{rank}}">
                    <div class="rank-badge">{{rank}}</div>
                    <span class="store-name">{{store_name}}</span>
                    <span class="store-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>

        <div class="leaderboard-panel">
            <h2 class="panel-title">Profit Ranking</h2>
            <div class="leaderboard-list">
                {{#each sales.wtd.top15_profit}}
                <div class="leaderboard-item rank-{{rank}}">
                    <div class="rank-badge">{{rank}}</div>
                    <span class="store-name">{{store_name}}</span>
                    <span class="store-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>
    </div>

    <div class="screen-footer">
        <span class="footer-text">Data refreshes every 5 minutes</span>
    </div>
</div>"""
        screen.save()
    except ScreenDesign.DoesNotExist:
        pass

    # Update MTD Rankings
    try:
        screen = ScreenDesign.objects.get(slug='jumpca-mtd-rankings')
        screen.name = "Jump.ca - Month to Date Top 15"
        screen.description = "Top 15 locations for Month to Date - Devices and Profit"
        screen.html_code = """<div class="screen-container">
    <div class="screen-header">
        <h1 class="screen-title">Month to Date - Top 15</h1>
    </div>

    <div class="single-column">
        <div class="leaderboard-panel">
            <h2 class="panel-title">Devices Ranking</h2>
            <div class="leaderboard-list">
                {{#each sales.mtd.top15_devices}}
                <div class="leaderboard-item rank-{{rank}}">
                    <div class="rank-badge">{{rank}}</div>
                    <span class="store-name">{{store_name}}</span>
                    <span class="store-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>

        <div class="leaderboard-panel">
            <h2 class="panel-title">Profit Ranking</h2>
            <div class="leaderboard-list">
                {{#each sales.mtd.top15_profit}}
                <div class="leaderboard-item rank-{{rank}}">
                    <div class="rank-badge">{{rank}}</div>
                    <span class="store-name">{{store_name}}</span>
                    <span class="store-value">{{value}}</span>
                </div>
                {{/each}}
            </div>
        </div>
    </div>

    <div class="screen-footer">
        <span class="footer-text">Data refreshes every 5 minutes</span>
    </div>
</div>"""
        screen.save()
    except ScreenDesign.DoesNotExist:
        pass


def revert_rankings(apps, schema_editor):
    """Revert (no-op)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0021_rankings_top20'),
    ]

    operations = [
        migrations.RunPython(update_rankings_to_top15, revert_rankings),
    ]
