# Generated by Django 4.2

from django.db import migrations

# Updated CSS with white store values instead of yellow
JUMPCA_CSS_WHITE_VALUES = """/* Jump.ca Branded Screen - Square styling, 315° gradient, white values */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

.screen-container {
    height: 100vh;
    width: 100vw;
    padding: 2vh 3vw;
    background: linear-gradient(315deg, #FAA41A 5%, #E44398 15%, #253746 35%, #00A98E 80%);
    overflow: hidden;
    display: flex;
    flex-direction: column;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

/* Header */
.screen-header {
    text-align: center;
    height: 12vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
    flex-shrink: 0;
}

.screen-title {
    font-size: 5vh;
    font-weight: 700;
    color: #ffffff;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    text-shadow: 0 2px 10px rgba(0,0,0,0.3);
}

.screen-subtitle {
    font-size: 2.5vh;
    color: rgba(255, 255, 255, 0.9);
    font-weight: 500;
    margin-top: 0.5vh;
}

/* Totals Section */
.totals-section {
    display: flex;
    justify-content: center;
    gap: 4vw;
    height: 12vh;
    margin: 1vh 0;
    flex-shrink: 0;
}

.total-card {
    background: rgba(255, 255, 255, 0.15);
    backdrop-filter: blur(10px);
    border: 1px solid rgba(255, 255, 255, 0.2);
    padding: 1.5vh 4vw;
    text-align: center;
    display: flex;
    flex-direction: column;
    justify-content: center;
}

.total-label {
    font-size: 2vh;
    color: rgba(255, 255, 255, 0.8);
    text-transform: uppercase;
    letter-spacing: 0.05em;
    margin-bottom: 0.5vh;
}

.total-value {
    font-size: 4.5vh;
    font-weight: 700;
    color: #ffffff;
    text-shadow: 0 2px 8px rgba(0,0,0,0.2);
}

/* Two Column Layout */
.two-column {
    flex: 1;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 2vw;
    min-height: 0;
    overflow: hidden;
}

/* Single Column Layout (for rankings) */
.single-column {
    flex: 1;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 2vw;
    min-height: 0;
    overflow: hidden;
}

/* Leaderboard Panel - Square styling */
.leaderboard-panel {
    background: rgba(0, 0, 0, 0.25);
    backdrop-filter: blur(10px);
    border: 1px solid rgba(255, 255, 255, 0.1);
    padding: 1.5vh 1.5vw;
    display: flex;
    flex-direction: column;
    overflow: hidden;
}

.panel-title {
    font-size: 2.2vh;
    font-weight: 600;
    color: #ffffff;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    margin-bottom: 1vh;
    flex-shrink: 0;
    text-align: center;
}

.leaderboard-list {
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 0.8vh;
    overflow: hidden;
}

.leaderboard-item {
    display: flex;
    align-items: center;
    padding: 0 1.5vw;
    background: rgba(255, 255, 255, 0.08);
    border: 1px solid rgba(255, 255, 255, 0.1);
    flex: 1;
    min-height: 0;
}

.leaderboard-item.rank-1 {
    background: linear-gradient(90deg, rgba(250, 164, 26, 0.3) 0%, rgba(250, 164, 26, 0.1) 100%);
    border-color: rgba(250, 164, 26, 0.4);
}

.leaderboard-item.rank-2 {
    background: linear-gradient(90deg, rgba(228, 67, 152, 0.2) 0%, rgba(228, 67, 152, 0.05) 100%);
    border-color: rgba(228, 67, 152, 0.3);
}

.leaderboard-item.rank-3 {
    background: linear-gradient(90deg, rgba(0, 169, 142, 0.2) 0%, rgba(0, 169, 142, 0.05) 100%);
    border-color: rgba(0, 169, 142, 0.3);
}

.rank-badge {
    width: 4vh;
    height: 4vh;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 2.2vh;
    font-weight: 700;
    color: #fff;
    background: rgba(37, 55, 70, 0.6);
    border: 2px solid rgba(37, 55, 70, 0.8);
    margin-right: 1.5vw;
    flex-shrink: 0;
}

.rank-1 .rank-badge {
    background: #FAA41A;
    border-color: #FAA41A;
    color: #253746;
}

.rank-2 .rank-badge {
    background: #E44398;
    border-color: #E44398;
}

.rank-3 .rank-badge {
    background: #00A98E;
    border-color: #00A98E;
}

.store-name {
    flex: 1;
    font-size: 2.2vh;
    font-weight: 500;
    color: #ffffff;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.store-value {
    font-size: 2.8vh;
    font-weight: 700;
    color: #ffffff;
    flex-shrink: 0;
    padding-left: 1vw;
}

/* Footer */
.screen-footer {
    height: 4vh;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
}

.footer-text {
    font-size: 1.5vh;
    color: rgba(255, 255, 255, 0.5);
}
"""


def update_rankings_white_values(apps, schema_editor):
    """Update ranking screens to use white values instead of yellow."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')

    # Update all ranking screens with new CSS
    ranking_slugs = [
        'jumpca-today-rankings',
        'jumpca-wtd-rankings',
        'jumpca-mtd-rankings',
    ]

    for slug in ranking_slugs:
        try:
            screen = ScreenDesign.objects.get(slug=slug)
            screen.css_code = JUMPCA_CSS_WHITE_VALUES
            screen.save()
        except ScreenDesign.DoesNotExist:
            pass


def revert_rankings_white_values(apps, schema_editor):
    """Revert (no-op)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0022_rankings_top15'),
    ]

    operations = [
        migrations.RunPython(update_rankings_white_values, revert_rankings_white_values),
    ]
