# Generated by Django 4.2

from django.db import migrations

# Jump.ca Dashboard with The Grid styling
JUMPCA_GRID_STYLE_CSS = """/* Jump.ca Dashboard - The Grid Design System */
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Roboto+Mono:wght@400;500;600;700&display=swap');

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

/* Main container with 3D horizon grid background */
.dashboard-container {
    height: 100vh;
    width: 100vw;
    padding: 3vh 3vw;
    overflow: hidden;
    display: flex;
    flex-direction: column;
    font-family: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    position: relative;
    background-color: #0b0b0b;
}

/* 3D Horizon Grid Background - Tron-style floor grid */
.dashboard-container::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 0;
    background-color: #0b0b0b;
    background-image:
        /* Horizontal lines with perspective density */
        repeating-linear-gradient(
            0deg,
            transparent,
            transparent 39px,
            rgba(0, 168, 141, 0.12) 39px,
            rgba(0, 168, 141, 0.12) 40px
        ),
        /* Vertical lines */
        repeating-linear-gradient(
            90deg,
            transparent,
            transparent 59px,
            rgba(0, 168, 141, 0.08) 59px,
            rgba(0, 168, 141, 0.08) 60px
        ),
        /* Gradient fade for horizon effect */
        linear-gradient(
            180deg,
            rgba(11, 11, 11, 1) 0%,
            rgba(11, 11, 11, 0.6) 40%,
            rgba(11, 11, 11, 0.8) 70%,
            rgba(11, 11, 11, 0.95) 100%
        );
    pointer-events: none;
    transform-origin: center bottom;
    transform: perspective(800px) rotateX(2deg) scale(1.1);
    opacity: 0.7;
}

/* Content wrapper above background */
.dashboard-content {
    position: relative;
    z-index: 1;
    display: flex;
    flex-direction: column;
    height: 100%;
}

/* Header */
.dashboard-header {
    text-align: center;
    height: 12vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
    flex-shrink: 0;
}

.company-name {
    font-size: 5vh;
    font-weight: 700;
    margin: 0;
    color: #ffffff;
    letter-spacing: -0.02em;
}

.company-name .highlight {
    color: #00a88d;
}

.dashboard-subtitle {
    font-size: 1.8vh;
    color: rgba(255, 255, 255, 0.5);
    text-transform: uppercase;
    letter-spacing: 0.15em;
    margin-top: 0.5vh;
    font-family: "Roboto Mono", ui-monospace, monospace;
}

/* Metrics Grid - 4 columns */
.metrics-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 0;
    height: 28vh;
    margin: 2vh 0;
    flex-shrink: 0;
}

/* Card-glass style metric cards */
.metric-card {
    background: #0b0b0b;
    border: 1px solid rgba(255, 255, 255, 0.10);
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    padding: 2vh 1vw;
    transition: border-color 0.15s ease-out, background 0.15s ease-out;
}

.metric-card:hover {
    border-color: rgba(0, 168, 141, 0.6);
    background: rgba(255, 255, 255, 0.03);
}

.metric-label {
    font-size: 1.6vh;
    color: rgba(255, 255, 255, 0.5);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1.5vh;
    font-family: "Roboto Mono", ui-monospace, monospace;
}

.metric-value {
    font-size: 5vh;
    font-weight: 700;
    color: #ffffff;
    line-height: 1;
    font-family: "Roboto Mono", ui-monospace, monospace;
}

.metric-value.primary {
    color: #00a88d;
}

.metric-value.accent {
    color: #E44398;
}

.metric-sub {
    font-size: 1.8vh;
    color: rgba(255, 255, 255, 0.4);
    margin-top: 1vh;
    font-family: "Roboto Mono", ui-monospace, monospace;
}

/* Leaderboard Section - Two columns */
.leaderboard-row {
    flex: 1;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 0;
    min-height: 0;
    overflow: hidden;
}

.leaderboard-panel {
    background: #0b0b0b;
    border: 1px solid rgba(255, 255, 255, 0.10);
    padding: 2vh 2vw;
    display: flex;
    flex-direction: column;
    min-height: 0;
    overflow: hidden;
}

.leaderboard-panel:first-child {
    border-right: none;
}

.panel-title {
    font-size: 1.8vh;
    font-weight: 600;
    color: rgba(255, 255, 255, 0.6);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1.5vh;
    flex-shrink: 0;
    font-family: "Roboto Mono", ui-monospace, monospace;
}

.leaderboard-list {
    display: flex;
    flex-direction: column;
    gap: 0.6vh;
    flex: 1;
    min-height: 0;
    overflow: hidden;
}

.leaderboard-item {
    display: flex;
    align-items: center;
    padding: 0 1.5vw;
    background: rgba(255, 255, 255, 0.02);
    border: 1px solid rgba(255, 255, 255, 0.05);
    flex: 1;
    min-height: 0;
    transition: border-color 0.15s ease-out, background 0.15s ease-out;
}

.leaderboard-item:hover {
    border-color: rgba(0, 168, 141, 0.4);
    background: rgba(255, 255, 255, 0.04);
}

/* Rank Badge - Square style */
.rank-badge {
    width: 3.5vh;
    height: 3.5vh;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 1.8vh;
    font-weight: 700;
    color: rgba(255, 255, 255, 0.4);
    background: rgba(255, 255, 255, 0.05);
    border: 1px solid rgba(255, 255, 255, 0.1);
    margin-right: 1.5vw;
    flex-shrink: 0;
    font-family: "Roboto Mono", ui-monospace, monospace;
}

/* Gold/Silver/Bronze for top 3 */
.leaderboard-item:nth-child(1) .rank-badge {
    background: #FFD700;
    border-color: #FFD700;
    color: #0b0b0b;
}

.leaderboard-item:nth-child(2) .rank-badge {
    background: #C0C0C0;
    border-color: #C0C0C0;
    color: #0b0b0b;
}

.leaderboard-item:nth-child(3) .rank-badge {
    background: #CD7F32;
    border-color: #CD7F32;
    color: #ffffff;
}

.store-name {
    flex: 1;
    font-size: 2vh;
    font-weight: 500;
    color: #ffffff;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    min-width: 0;
}

.store-value {
    font-size: 2.2vh;
    font-weight: 700;
    color: #00a88d;
    flex-shrink: 0;
    padding-left: 1vw;
    font-family: "Roboto Mono", ui-monospace, monospace;
}

/* Footer */
.dashboard-footer {
    height: 4vh;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    border-top: 1px solid rgba(255, 255, 255, 0.05);
    margin-top: 1vh;
}

.footer-text {
    font-size: 1.4vh;
    color: rgba(255, 255, 255, 0.3);
    font-family: "Roboto Mono", ui-monospace, monospace;
    text-transform: uppercase;
    letter-spacing: 0.1em;
}

.footer-text .highlight {
    color: #00a88d;
}
"""

JUMPCA_GRID_STYLE_HTML = """<div class="dashboard-container">
    <div class="dashboard-content">
        <div class="dashboard-header">
            <h1 class="company-name">Jump<span class="highlight">.ca</span> Sales</h1>
            <p class="dashboard-subtitle">Live Performance Dashboard</p>
        </div>

        <div class="metrics-grid">
            <div class="metric-card">
                <div class="metric-label">Today's Profit</div>
                <div class="metric-value primary">{{sales.today.totals.profit}}</div>
                <div class="metric-sub">{{sales.today.totals.invoice_count}} invoices</div>
            </div>

            <div class="metric-card">
                <div class="metric-label">Week to Date</div>
                <div class="metric-value">{{sales.wtd.totals.profit}}</div>
                <div class="metric-sub">{{sales.wtd.totals.devices}} devices</div>
            </div>

            <div class="metric-card">
                <div class="metric-label">Month to Date</div>
                <div class="metric-value">{{sales.mtd.totals.profit}}</div>
                <div class="metric-sub">{{sales.mtd.totals.devices}} devices</div>
            </div>

            <div class="metric-card">
                <div class="metric-label">Today's Devices</div>
                <div class="metric-value accent">{{sales.today.totals.devices}}</div>
                <div class="metric-sub">phones sold</div>
            </div>
        </div>

        <div class="leaderboard-row">
            <div class="leaderboard-panel">
                <h2 class="panel-title">Top 5 Profit Today</h2>
                <div class="leaderboard-list">
                    {{#each sales.today.top5_profit}}
                    <div class="leaderboard-item">
                        <div class="rank-badge">{{rank}}</div>
                        <span class="store-name">{{store_name}}</span>
                        <span class="store-value">{{value}}</span>
                    </div>
                    {{/each}}
                </div>
            </div>

            <div class="leaderboard-panel">
                <h2 class="panel-title">Top 5 Devices Today</h2>
                <div class="leaderboard-list">
                    {{#each sales.today.top5_devices}}
                    <div class="leaderboard-item">
                        <div class="rank-badge">{{rank}}</div>
                        <span class="store-name">{{store_name}}</span>
                        <span class="store-value">{{value}}</span>
                    </div>
                    {{/each}}
                </div>
            </div>
        </div>

        <div class="dashboard-footer">
            <span class="footer-text">Data refreshes every <span class="highlight">5 minutes</span></span>
        </div>
    </div>
</div>"""


def create_grid_style_dashboard(apps, schema_editor):
    """Create new Jump.ca dashboard with The Grid design system styling."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')

    # Create new screen design
    ScreenDesign.objects.create(
        name="Jump.ca - Dashboard (Grid Style)",
        slug="jumpca-dashboard-grid-style",
        description="Jump.ca dashboard using The Grid design system - 3D horizon grid background, card-glass panels, mono fonts",
        html_code=JUMPCA_GRID_STYLE_HTML,
        css_code=JUMPCA_GRID_STYLE_CSS,
        js_code="",
        notes="New dashboard design based on The Grid's Lambda.ai-inspired aesthetic with Jump.ca teal (#00a88d) as primary color",
        is_active=True,
    )


def remove_grid_style_dashboard(apps, schema_editor):
    """Remove the new dashboard."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')
    ScreenDesign.objects.filter(slug='jumpca-dashboard-grid-style').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0023_rankings_white_values'),
    ]

    operations = [
        migrations.RunPython(create_grid_style_dashboard, remove_grid_style_dashboard),
    ]
