# Generated by Django 4.2

from django.db import migrations

# Jump.ca Dashboard V2 with interactive canvas grid and proper fonts
JUMPCA_GRID_STYLE_CSS_V2 = """/* Jump.ca Dashboard V2 - Interactive Canvas Grid */
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Roboto+Mono:wght@400;500;600;700&display=swap');

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

/* Main container */
.dashboard-container {
    height: 100vh;
    width: 100vw;
    overflow: hidden;
    position: relative;
    background-color: #050506;
}

/* Canvas for interactive grid - fills entire background */
.grid-canvas {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 0;
}

/* Content wrapper above canvas */
.dashboard-content {
    position: relative;
    z-index: 1;
    display: flex;
    flex-direction: column;
    height: 100%;
    padding: 3vh 3vw;
}

/* Header */
.dashboard-header {
    text-align: center;
    height: 10vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
    flex-shrink: 0;
}

.company-name {
    font-size: 5vh;
    font-weight: 700;
    margin: 0;
    color: #ffffff;
    letter-spacing: -0.02em;
    font-family: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

.company-name .highlight {
    color: #00a88d;
}

.dashboard-subtitle {
    font-size: 1.6vh;
    color: rgba(255, 255, 255, 0.45);
    text-transform: uppercase;
    letter-spacing: 0.2em;
    margin-top: 0.5vh;
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
}

/* Metrics Grid - 4 columns with gaps */
.metrics-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 1.5vw;
    height: 26vh;
    margin: 2vh 0;
    flex-shrink: 0;
}

/* Card-glass style metric cards */
.metric-card {
    background: rgba(11, 11, 11, 0.85);
    border: 1px solid rgba(255, 255, 255, 0.08);
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    padding: 2vh 1vw;
    transition: border-color 0.15s ease-out, background 0.15s ease-out;
}

.metric-label {
    font-size: 1.5vh;
    color: rgba(255, 255, 255, 0.45);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1.5vh;
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
}

.metric-value {
    font-size: 5vh;
    font-weight: 700;
    color: #ffffff;
    line-height: 1;
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
}

.metric-value.primary {
    color: #00a88d;
}

.metric-value.accent {
    color: #E44398;
}

.metric-sub {
    font-size: 1.6vh;
    color: rgba(255, 255, 255, 0.35);
    margin-top: 1vh;
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
}

/* Leaderboard Section - Two columns with gap */
.leaderboard-row {
    flex: 1;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1.5vw;
    min-height: 0;
    overflow: hidden;
}

.leaderboard-panel {
    background: rgba(11, 11, 11, 0.85);
    border: 1px solid rgba(255, 255, 255, 0.08);
    padding: 2vh 2vw;
    display: flex;
    flex-direction: column;
    min-height: 0;
    overflow: hidden;
}

.panel-title {
    font-size: 1.6vh;
    font-weight: 600;
    color: rgba(255, 255, 255, 0.5);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1.5vh;
    flex-shrink: 0;
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
}

.leaderboard-list {
    display: flex;
    flex-direction: column;
    gap: 0.8vh;
    flex: 1;
    min-height: 0;
    overflow: hidden;
}

.leaderboard-item {
    display: flex;
    align-items: center;
    padding: 0 1.5vw;
    background: rgba(255, 255, 255, 0.02);
    border: 1px solid rgba(255, 255, 255, 0.04);
    flex: 1;
    min-height: 0;
}

/* Rank Badge - Square style */
.rank-badge {
    width: 3.5vh;
    height: 3.5vh;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 1.8vh;
    font-weight: 700;
    color: rgba(255, 255, 255, 0.35);
    background: rgba(255, 255, 255, 0.03);
    border: 1px solid rgba(255, 255, 255, 0.08);
    margin-right: 1.5vw;
    flex-shrink: 0;
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
}

/* Gold/Silver/Bronze for top 3 */
.leaderboard-item:nth-child(1) .rank-badge {
    background: #FFD700;
    border-color: #FFD700;
    color: #0b0b0b;
}

.leaderboard-item:nth-child(2) .rank-badge {
    background: #C0C0C0;
    border-color: #C0C0C0;
    color: #0b0b0b;
}

.leaderboard-item:nth-child(3) .rank-badge {
    background: #CD7F32;
    border-color: #CD7F32;
    color: #ffffff;
}

.store-name {
    flex: 1;
    font-size: 2vh;
    font-weight: 500;
    color: #ffffff;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    min-width: 0;
    font-family: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

.store-value {
    font-size: 2.2vh;
    font-weight: 700;
    color: #00a88d;
    flex-shrink: 0;
    padding-left: 1vw;
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
}

/* Footer */
.dashboard-footer {
    height: 4vh;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    margin-top: 1vh;
}

.footer-text {
    font-size: 1.3vh;
    color: rgba(255, 255, 255, 0.25);
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
    text-transform: uppercase;
    letter-spacing: 0.15em;
}

.footer-text .highlight {
    color: #00a88d;
}
"""

JUMPCA_GRID_STYLE_HTML_V2 = """<div class="dashboard-container">
    <canvas class="grid-canvas" id="gridCanvas"></canvas>

    <div class="dashboard-content">
        <div class="dashboard-header">
            <h1 class="company-name">Jump<span class="highlight">.ca</span> Sales</h1>
            <p class="dashboard-subtitle">Live Performance Dashboard</p>
        </div>

        <div class="metrics-grid">
            <div class="metric-card">
                <div class="metric-label">Today's Profit</div>
                <div class="metric-value primary">{{sales.today.totals.profit}}</div>
                <div class="metric-sub">{{sales.today.totals.invoice_count}} invoices</div>
            </div>

            <div class="metric-card">
                <div class="metric-label">Week to Date</div>
                <div class="metric-value">{{sales.wtd.totals.profit}}</div>
                <div class="metric-sub">{{sales.wtd.totals.devices}} devices</div>
            </div>

            <div class="metric-card">
                <div class="metric-label">Month to Date</div>
                <div class="metric-value">{{sales.mtd.totals.profit}}</div>
                <div class="metric-sub">{{sales.mtd.totals.devices}} devices</div>
            </div>

            <div class="metric-card">
                <div class="metric-label">Today's Devices</div>
                <div class="metric-value accent">{{sales.today.totals.devices}}</div>
                <div class="metric-sub">phones sold</div>
            </div>
        </div>

        <div class="leaderboard-row">
            <div class="leaderboard-panel">
                <h2 class="panel-title">Top 5 Profit Today</h2>
                <div class="leaderboard-list">
                    {{#each sales.today.top5_profit}}
                    <div class="leaderboard-item">
                        <div class="rank-badge">{{rank}}</div>
                        <span class="store-name">{{store_name}}</span>
                        <span class="store-value">{{value}}</span>
                    </div>
                    {{/each}}
                </div>
            </div>

            <div class="leaderboard-panel">
                <h2 class="panel-title">Top 5 Devices Today</h2>
                <div class="leaderboard-list">
                    {{#each sales.today.top5_devices}}
                    <div class="leaderboard-item">
                        <div class="rank-badge">{{rank}}</div>
                        <span class="store-name">{{store_name}}</span>
                        <span class="store-value">{{value}}</span>
                    </div>
                    {{/each}}
                </div>
            </div>
        </div>

        <div class="dashboard-footer">
            <span class="footer-text">Data refreshes every <span class="highlight">5 minutes</span></span>
        </div>
    </div>
</div>"""

# JavaScript for the interactive canvas grid with fixed "mouse" position
JUMPCA_GRID_STYLE_JS = """
(function() {
    var canvas = document.getElementById('gridCanvas');
    if (!canvas) return;

    var ctx = canvas.getContext('2d');
    var cellSize = 80;

    // Fixed "mouse" position - upper left area for nice glow effect
    var fixedMouseX = null;
    var fixedMouseY = null;

    function resizeCanvas() {
        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;

        // Set fixed mouse position after resize - upper-left quadrant
        fixedMouseX = canvas.width * 0.25;
        fixedMouseY = canvas.height * 0.35;

        drawGrid();
    }

    function drawGrid() {
        ctx.clearRect(0, 0, canvas.width, canvas.height);

        var mouseX = fixedMouseX;
        var mouseY = fixedMouseY;
        var baseAlpha = 0.018;
        var segmentRadius = cellSize * 3.5;

        // Vertical lines
        for (var x = 0; x <= canvas.width; x += cellSize) {
            var dx = (mouseX != null) ? (x - mouseX) : null;
            var distanceFactor = 0;

            if (mouseX != null && mouseY != null) {
                var radialDistance = Math.abs(dx);
                distanceFactor = Math.max(0, 1 - radialDistance / (cellSize * 6));
            }

            var alpha = baseAlpha + distanceFactor * 0.05;
            ctx.strokeStyle = "rgba(255,255,255," + alpha.toFixed(3) + ")";
            ctx.beginPath();
            ctx.moveTo(x + 0.5, 0);
            ctx.lineTo(x + 0.5, canvas.height);
            ctx.stroke();

            // Add colored glow near the fixed point
            if (mouseX != null && mouseY != null && distanceFactor > 0) {
                var chromaIntensity = distanceFactor * 0.25;
                if (Math.abs(dx) < cellSize * 0.5) {
                    chromaIntensity = Math.min(0.6, chromaIntensity * 2);
                }

                var yStart = Math.max(0, mouseY - segmentRadius);
                var yEnd = Math.min(canvas.height, mouseY + segmentRadius);

                // Use teal (#00a88d) on left, pink (#E44398) on right
                var color = (dx < 0) ? "rgba(0,168,141," : "rgba(228,67,152,";
                var grad = ctx.createLinearGradient(0, yStart, 0, yEnd);
                var mid = Math.max(0, Math.min(1, (mouseY - yStart) / (yEnd - yStart)));
                var maxAlpha = chromaIntensity;

                grad.addColorStop(0.0, color + "0)");
                if (mid - 0.15 > 0) grad.addColorStop(mid - 0.15, color + (maxAlpha * 0.3).toFixed(3) + ")");
                if (mid - 0.05 > 0) grad.addColorStop(mid - 0.05, color + (maxAlpha * 0.8).toFixed(3) + ")");
                grad.addColorStop(mid, color + maxAlpha.toFixed(3) + ")");
                if (mid + 0.05 < 1) grad.addColorStop(mid + 0.05, color + (maxAlpha * 0.8).toFixed(3) + ")");
                if (mid + 0.15 < 1) grad.addColorStop(mid + 0.15, color + (maxAlpha * 0.3).toFixed(3) + ")");
                grad.addColorStop(1.0, color + "0)");

                ctx.strokeStyle = grad;
                ctx.beginPath();
                ctx.moveTo(x + 0.5, yStart);
                ctx.lineTo(x + 0.5, yEnd);
                ctx.stroke();
            }
        }

        // Horizontal lines
        for (var y = 0; y <= canvas.height; y += cellSize) {
            var dy = (mouseY != null) ? (y - mouseY) : null;
            var distanceFactorY = 0;

            if (mouseX != null && mouseY != null) {
                var radialDistanceY = Math.abs(dy);
                distanceFactorY = Math.max(0, 1 - radialDistanceY / (cellSize * 4));
            }

            var alphaY = baseAlpha + distanceFactorY * 0.05;
            ctx.strokeStyle = "rgba(255,255,255," + alphaY.toFixed(3) + ")";
            ctx.beginPath();
            ctx.moveTo(0, y + 0.5);
            ctx.lineTo(canvas.width, y + 0.5);
            ctx.stroke();

            // Add colored glow near the fixed point
            if (mouseX != null && mouseY != null && distanceFactorY > 0) {
                var chromaIntensityY = distanceFactorY * 0.25;
                if (Math.abs(dy) < cellSize * 0.5) {
                    chromaIntensityY = Math.min(0.6, chromaIntensityY * 2);
                }

                var xStart = Math.max(0, mouseX - segmentRadius);
                var xEnd = Math.min(canvas.width, mouseX + segmentRadius);

                // Use teal above, white below (subtle)
                var color = (dy < 0) ? "rgba(0,168,141," : "rgba(255,255,255,";
                var grad = ctx.createLinearGradient(xStart, 0, xEnd, 0);
                var mid = Math.max(0, Math.min(1, (mouseX - xStart) / (xEnd - xStart)));
                var maxAlpha = chromaIntensityY;

                if (dy >= 0) {
                    maxAlpha = maxAlpha * 0.4;
                }

                grad.addColorStop(0.0, color + "0)");
                if (mid - 0.15 > 0) grad.addColorStop(mid - 0.15, color + (maxAlpha * 0.3).toFixed(3) + ")");
                if (mid - 0.05 > 0) grad.addColorStop(mid - 0.05, color + (maxAlpha * 0.8).toFixed(3) + ")");
                grad.addColorStop(mid, color + maxAlpha.toFixed(3) + ")");
                if (mid + 0.05 < 1) grad.addColorStop(mid + 0.05, color + (maxAlpha * 0.8).toFixed(3) + ")");
                if (mid + 0.15 < 1) grad.addColorStop(mid + 0.15, color + (maxAlpha * 0.3).toFixed(3) + ")");
                grad.addColorStop(1.0, color + "0)");

                ctx.strokeStyle = grad;
                ctx.beginPath();
                ctx.moveTo(xStart, y + 0.5);
                ctx.lineTo(xEnd, y + 0.5);
                ctx.stroke();
            }
        }
    }

    window.addEventListener('resize', resizeCanvas);
    resizeCanvas();
})();
"""


def update_grid_style_dashboard(apps, schema_editor):
    """Update Jump.ca Grid Style dashboard with interactive canvas and proper spacing."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')

    try:
        dashboard = ScreenDesign.objects.get(slug='jumpca-dashboard-grid-style')
        dashboard.html_code = JUMPCA_GRID_STYLE_HTML_V2
        dashboard.css_code = JUMPCA_GRID_STYLE_CSS_V2
        dashboard.js_code = JUMPCA_GRID_STYLE_JS
        dashboard.save()
    except ScreenDesign.DoesNotExist:
        pass


def revert_grid_style_dashboard(apps, schema_editor):
    """Revert (no-op)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0024_jumpca_dashboard_grid_style'),
    ]

    operations = [
        migrations.RunPython(update_grid_style_dashboard, revert_grid_style_dashboard),
    ]
