# Generated by Django 4.2

from django.db import migrations

# Updated HTML without sub-labels on metric cards
JUMPCA_GRID_STYLE_HTML_V6 = """<div class="dashboard-container">
    <canvas class="grid-canvas" id="gridCanvas"></canvas>

    <div class="dashboard-content">
        <div class="dashboard-header">
            <img src="/static/digital_signage/jump_logo_white.png" alt="Jump.ca" class="company-logo">
            <p class="dashboard-subtitle">Live Sales Dashboard</p>
        </div>

        <div class="metrics-grid">
            <div class="metric-card">
                <div class="metric-label">Today's Profit</div>
                <div class="metric-value primary">{{sales.today.totals.profit}}</div>
            </div>

            <div class="metric-card">
                <div class="metric-label">Month to Date</div>
                <div class="metric-value">{{sales.mtd.totals.profit}}</div>
            </div>

            <div class="metric-card">
                <div class="metric-label">Today's Devices</div>
                <div class="metric-value accent">{{sales.today.totals.devices}}</div>
            </div>

            <div class="metric-card">
                <div class="metric-label">MTD Devices</div>
                <div class="metric-value accent">{{sales.mtd.totals.devices}}</div>
            </div>
        </div>

        <div class="leaderboard-row">
            <div class="leaderboard-panel">
                <h2 class="panel-title">Top 5 Profit Today</h2>
                <div class="leaderboard-list">
                    {{#each sales.today.top5_profit}}
                    <div class="leaderboard-item">
                        <div class="rank-badge">{{rank}}</div>
                        <span class="store-name">{{store_name}}</span>
                        <span class="store-value">{{value}}</span>
                    </div>
                    {{/each}}
                </div>
            </div>

            <div class="leaderboard-panel leaderboard-devices">
                <h2 class="panel-title">Top 5 Devices Today</h2>
                <div class="leaderboard-list">
                    {{#each sales.today.top5_devices}}
                    <div class="leaderboard-item">
                        <div class="rank-badge">{{rank}}</div>
                        <span class="store-name">{{store_name}}</span>
                        <span class="store-value">{{value}}</span>
                    </div>
                    {{/each}}
                </div>
            </div>
        </div>

        <div class="dashboard-footer">
            <span class="footer-text">Data refreshes every <span class="highlight">5 minutes</span></span>
        </div>
    </div>
</div>"""


def remove_sublabels(apps, schema_editor):
    """Remove sub-labels from metric cards."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')

    try:
        dashboard = ScreenDesign.objects.get(slug='jumpca-dashboard-grid-style')
        dashboard.html_code = JUMPCA_GRID_STYLE_HTML_V6
        dashboard.save()
    except ScreenDesign.DoesNotExist:
        pass


def revert_sublabels(apps, schema_editor):
    """Revert (no-op)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0028_jumpca_dashboard_pink_devices'),
    ]

    operations = [
        migrations.RunPython(remove_sublabels, revert_sublabels),
    ]
