# Generated by Django 4.2

from django.db import migrations

# Updated CSS with larger stacked powered-by badge
JUMPCA_GRID_STYLE_CSS_V6 = """/* Jump.ca Dashboard V6 - Tweaks */
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Roboto+Mono:wght@400;500;600;700&display=swap');

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

/* Main container */
.dashboard-container {
    height: 100vh;
    width: 100vw;
    overflow: hidden;
    position: relative;
    background-color: #050506;
}

/* Canvas for interactive grid - fills entire background */
.grid-canvas {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 0;
}

/* Content wrapper above canvas */
.dashboard-content {
    position: relative;
    z-index: 1;
    display: flex;
    flex-direction: column;
    height: 100%;
    padding: 3vh 3vw;
}

/* Powered by badge - top right corner, stacked vertically */
.powered-by {
    position: absolute;
    top: 2vh;
    right: 3vw;
    display: flex;
    flex-direction: column;
    align-items: flex-end;
    gap: 0.5vh;
    z-index: 10;
}

.powered-by-text {
    font-size: 1.2vh;
    color: rgba(255, 255, 255, 0.35);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
}

.powered-by-logo {
    height: 5vh;
    width: auto;
    opacity: 0.6;
}

/* Header */
.dashboard-header {
    text-align: center;
    height: 12vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    flex-shrink: 0;
}

.company-logo {
    height: 6vh;
    width: auto;
    margin-bottom: 1vh;
}

.dashboard-subtitle {
    font-size: 1.6vh;
    color: rgba(255, 255, 255, 0.45);
    text-transform: uppercase;
    letter-spacing: 0.2em;
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
}

/* Metrics Grid - 4 columns with gaps */
.metrics-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 1.5vw;
    height: 26vh;
    margin: 2vh 0;
    flex-shrink: 0;
}

/* Card-glass style metric cards */
.metric-card {
    background: rgba(11, 11, 11, 0.85);
    border: 1px solid rgba(255, 255, 255, 0.08);
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    padding: 2vh 1vw;
    transition: border-color 0.15s ease-out, background 0.15s ease-out;
}

.metric-label {
    font-size: 1.5vh;
    color: rgba(255, 255, 255, 0.45);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1.5vh;
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
}

.metric-value {
    font-size: 5vh;
    font-weight: 700;
    color: #ffffff;
    line-height: 1;
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
}

.metric-value.primary {
    color: #00a88d;
}

.metric-value.accent {
    color: #E44398;
}

.metric-sub {
    font-size: 1.6vh;
    color: rgba(255, 255, 255, 0.35);
    margin-top: 1vh;
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
}

/* Leaderboard Section - Two columns with gap */
.leaderboard-row {
    flex: 1;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1.5vw;
    min-height: 0;
    overflow: hidden;
}

.leaderboard-panel {
    background: rgba(11, 11, 11, 0.85);
    border: 1px solid rgba(255, 255, 255, 0.08);
    padding: 2vh 2vw;
    display: flex;
    flex-direction: column;
    min-height: 0;
    overflow: hidden;
}

.panel-title {
    font-size: 1.6vh;
    font-weight: 600;
    color: rgba(255, 255, 255, 0.5);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1.5vh;
    flex-shrink: 0;
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
}

.leaderboard-list {
    display: flex;
    flex-direction: column;
    gap: 0.8vh;
    flex: 1;
    min-height: 0;
    overflow: hidden;
}

.leaderboard-item {
    display: flex;
    align-items: center;
    padding: 0 1.5vw;
    background: rgba(255, 255, 255, 0.02);
    border: 1px solid rgba(255, 255, 255, 0.04);
    flex: 1;
    min-height: 0;
}

/* Rank Badge - Square style */
.rank-badge {
    width: 3.5vh;
    height: 3.5vh;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 1.8vh;
    font-weight: 700;
    color: rgba(255, 255, 255, 0.35);
    background: rgba(255, 255, 255, 0.03);
    border: 1px solid rgba(255, 255, 255, 0.08);
    margin-right: 1.5vw;
    flex-shrink: 0;
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
}

/* Gold/Silver/Bronze for top 3 */
.leaderboard-item:nth-child(1) .rank-badge {
    background: #FFD700;
    border-color: #FFD700;
    color: #0b0b0b;
}

.leaderboard-item:nth-child(2) .rank-badge {
    background: #C0C0C0;
    border-color: #C0C0C0;
    color: #0b0b0b;
}

.leaderboard-item:nth-child(3) .rank-badge {
    background: #CD7F32;
    border-color: #CD7F32;
    color: #ffffff;
}

.store-name {
    flex: 1;
    font-size: 2vh;
    font-weight: 500;
    color: #ffffff;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    min-width: 0;
    font-family: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

.store-value {
    font-size: 2.2vh;
    font-weight: 700;
    color: #00a88d;
    flex-shrink: 0;
    padding-left: 1vw;
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
}

/* Pink values for devices leaderboard */
.leaderboard-devices .store-value {
    color: #E44398;
}

/* Footer */
.dashboard-footer {
    height: 4vh;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    margin-top: 1vh;
}

.footer-text {
    font-size: 1.3vh;
    color: rgba(255, 255, 255, 0.25);
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
    text-transform: uppercase;
    letter-spacing: 0.15em;
}

.footer-text .highlight {
    color: #00a88d;
}
"""

# Updated HTML - MTD Profit label, white MTD Devices value
JUMPCA_GRID_STYLE_HTML_V8 = """<div class="dashboard-container">
    <canvas class="grid-canvas" id="gridCanvas"></canvas>

    <div class="dashboard-content">
        <div class="powered-by">
            <span class="powered-by-text">Powered by</span>
            <img src="/static/digital_signage/grid_logo.png" alt="The Grid" class="powered-by-logo">
        </div>

        <div class="dashboard-header">
            <img src="/static/digital_signage/jump_logo_white.png" alt="Jump.ca" class="company-logo">
            <p class="dashboard-subtitle">Live Sales Dashboard</p>
        </div>

        <div class="metrics-grid">
            <div class="metric-card">
                <div class="metric-label">Today's Profit</div>
                <div class="metric-value primary">{{sales.today.totals.profit}}</div>
            </div>

            <div class="metric-card">
                <div class="metric-label">MTD Profit</div>
                <div class="metric-value">{{sales.mtd.totals.profit}}</div>
            </div>

            <div class="metric-card">
                <div class="metric-label">Today's Devices</div>
                <div class="metric-value accent">{{sales.today.totals.devices}}</div>
            </div>

            <div class="metric-card">
                <div class="metric-label">MTD Devices</div>
                <div class="metric-value">{{sales.mtd.totals.devices}}</div>
            </div>
        </div>

        <div class="leaderboard-row">
            <div class="leaderboard-panel">
                <h2 class="panel-title">Top 5 Profit Today</h2>
                <div class="leaderboard-list">
                    {{#each sales.today.top5_profit}}
                    <div class="leaderboard-item">
                        <div class="rank-badge">{{rank}}</div>
                        <span class="store-name">{{store_name}}</span>
                        <span class="store-value">{{value}}</span>
                    </div>
                    {{/each}}
                </div>
            </div>

            <div class="leaderboard-panel leaderboard-devices">
                <h2 class="panel-title">Top 5 Devices Today</h2>
                <div class="leaderboard-list">
                    {{#each sales.today.top5_devices}}
                    <div class="leaderboard-item">
                        <div class="rank-badge">{{rank}}</div>
                        <span class="store-name">{{store_name}}</span>
                        <span class="store-value">{{value}}</span>
                    </div>
                    {{/each}}
                </div>
            </div>
        </div>

        <div class="dashboard-footer">
            <span class="footer-text">Data refreshes every <span class="highlight">5 minutes</span></span>
        </div>
    </div>
</div>"""


def update_tweaks(apps, schema_editor):
    """Update dashboard with tweaks."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')

    try:
        dashboard = ScreenDesign.objects.get(slug='jumpca-dashboard-grid-style')
        dashboard.html_code = JUMPCA_GRID_STYLE_HTML_V8
        dashboard.css_code = JUMPCA_GRID_STYLE_CSS_V6
        dashboard.save()
    except ScreenDesign.DoesNotExist:
        pass


def revert_tweaks(apps, schema_editor):
    """Revert (no-op)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0030_jumpca_dashboard_powered_by'),
    ]

    operations = [
        migrations.RunPython(update_tweaks, revert_tweaks),
    ]
