# Generated by Django 4.2

from django.db import migrations

# Company Dashboard - Grid Style with Target Metrics
# Uses the same styling as jumpca-dashboard-grid-style but with different data:
# - Today's Devices, MTD Devices, % of Target, MTD Trending
# - Top 5 % of Target, Top 5 Trending

COMPANY_DASHBOARD_HTML = """<div class="dashboard-container">
    <canvas class="grid-canvas" id="gridCanvas"></canvas>

    <div class="dashboard-content">
        <div class="powered-by">
            <img src="/static/digital_signage/poweredbygrid.png" alt="Powered by The Grid" class="powered-by-logo">
        </div>

        <div class="dashboard-header">
            <img src="/static/digital_signage/jump_logo_white.png" alt="Jump.ca" class="company-logo">
            <p class="dashboard-subtitle">Company Performance Dashboard</p>
        </div>

        <div class="metrics-grid">
            <div class="metric-card">
                <div class="metric-label">Today's Devices</div>
                <div class="metric-value primary">{{sales.today.totals.devices}}</div>
            </div>

            <div class="metric-card">
                <div class="metric-label">MTD Devices</div>
                <div class="metric-value">{{sales.mtd.totals.devices}}</div>
            </div>

            <div class="metric-card">
                <div class="metric-label">% of Target</div>
                <div class="metric-value accent">{{sales.mtd.totals.pct_of_target}}</div>
            </div>

            <div class="metric-card">
                <div class="metric-label">MTD Trending</div>
                <div class="metric-value">{{sales.mtd.totals.trending}}</div>
            </div>
        </div>

        <div class="leaderboard-row">
            <div class="leaderboard-panel">
                <div class="metric-label">Top 5 % of Target</div>
                <div class="leaderboard-list">
                    {{#each sales.mtd.targets.devices.top5}}
                    <div class="leaderboard-item">
                        <div class="rank-badge">{{rank}}</div>
                        <span class="store-name">{{store_name}}</span>
                        <span class="store-value">{{pct_of_target}}</span>
                    </div>
                    {{/each}}
                </div>
            </div>

            <div class="leaderboard-panel">
                <div class="metric-label">Top 5 Trending</div>
                <div class="leaderboard-list">
                    {{#each sales.mtd.targets.devices.top5}}
                    <div class="leaderboard-item">
                        <div class="rank-badge">{{rank}}</div>
                        <span class="store-name">{{store_name}}</span>
                        <span class="store-value">{{trending}}</span>
                    </div>
                    {{/each}}
                </div>
            </div>
        </div>

        <div class="dashboard-footer">
            <span class="footer-text">Data refreshes every <span class="highlight">5 minutes</span></span>
        </div>
    </div>
</div>"""

COMPANY_DASHBOARD_CSS = """/* Company Dashboard - Grid Style */
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Montserrat:wght@400;500;600;700&family=Roboto+Mono:wght@400;500;600;700&display=swap');

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

/* Main container */
.dashboard-container {
    height: 100vh;
    width: 100vw;
    overflow: hidden;
    position: relative;
    background-color: #050506;
}

/* Canvas for interactive grid - fills entire background */
.grid-canvas {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 0;
}

/* Content wrapper above canvas */
.dashboard-content {
    position: relative;
    z-index: 1;
    display: flex;
    flex-direction: column;
    height: 100%;
    padding: 3vh 3vw;
}

/* Powered by badge - single combined image */
.powered-by {
    position: absolute;
    top: 3vh;
    right: 3vw;
    z-index: 10;
}

.powered-by-logo {
    height: 10vh;
    width: auto;
    opacity: 0.6;
}

/* Header */
.dashboard-header {
    text-align: center;
    height: 12vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    flex-shrink: 0;
}

.company-logo {
    height: 6vh;
    width: auto;
    margin-bottom: 1vh;
}

.dashboard-subtitle {
    font-size: 1.6vh;
    color: rgba(255, 255, 255, 0.45);
    text-transform: uppercase;
    letter-spacing: 0.2em;
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
}

/* Metrics Grid - 4 columns with gaps */
.metrics-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 1.5vw;
    height: 26vh;
    margin: 2vh 0;
    flex-shrink: 0;
}

/* Card-glass style metric cards */
.metric-card {
    background: rgba(11, 11, 11, 0.85);
    border: 1px solid rgba(255, 255, 255, 0.08);
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    padding: 2vh 1vw;
    transition: border-color 0.15s ease-out, background 0.15s ease-out;
}

.metric-label {
    font-size: 1.5vh;
    color: rgba(255, 255, 255, 0.45);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1.5vh;
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
}

/* Center metric-label in leaderboard panels */
.leaderboard-panel .metric-label {
    text-align: center;
    width: 100%;
}

.metric-value {
    font-size: 5vh;
    font-weight: 500;
    color: #ffffff;
    line-height: 1;
    font-family: "Montserrat", "Inter", sans-serif;
}

.metric-value.primary {
    color: #00a88d;
}

.metric-value.accent {
    color: #E44398;
}

.metric-sub {
    font-size: 1.6vh;
    color: rgba(255, 255, 255, 0.35);
    margin-top: 1vh;
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
}

/* Leaderboard Section - Two columns with gap */
.leaderboard-row {
    flex: 1;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1.5vw;
    min-height: 0;
    overflow: hidden;
}

.leaderboard-panel {
    background: rgba(11, 11, 11, 0.85);
    border: 1px solid rgba(255, 255, 255, 0.08);
    padding: 2vh 2vw;
    display: flex;
    flex-direction: column;
    min-height: 0;
    overflow: hidden;
}

.leaderboard-list {
    display: flex;
    flex-direction: column;
    gap: 0.8vh;
    flex: 1;
    min-height: 0;
    overflow: hidden;
}

.leaderboard-item {
    display: flex;
    align-items: center;
    padding: 0 1.5vw;
    background: rgba(255, 255, 255, 0.02);
    border: 1px solid rgba(255, 255, 255, 0.04);
    flex: 1;
    min-height: 0;
}

/* Rank Badge - Square style */
.rank-badge {
    width: 3.5vh;
    height: 3.5vh;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 1.8vh;
    font-weight: 500;
    color: rgba(255, 255, 255, 0.35);
    background: rgba(255, 255, 255, 0.03);
    border: 1px solid rgba(255, 255, 255, 0.08);
    margin-right: 1.5vw;
    flex-shrink: 0;
    font-family: "Montserrat", "Inter", sans-serif;
}

/* Gold/Silver/Bronze for top 3 - all with dark text */
.leaderboard-item:nth-child(1) .rank-badge {
    background: #D4AF37;
    border-color: #D4AF37;
    color: #0b0b0b;
}

.leaderboard-item:nth-child(2) .rank-badge {
    background: #C0C0C0;
    border-color: #C0C0C0;
    color: #0b0b0b;
}

.leaderboard-item:nth-child(3) .rank-badge {
    background: #A97142;
    border-color: #A97142;
    color: #0b0b0b;
}

.store-name {
    flex: 1;
    font-size: 2vh;
    font-weight: 500;
    color: rgba(255, 255, 255, 0.45);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    min-width: 0;
    font-family: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

.store-value {
    font-size: 2.2vh;
    font-weight: 500;
    color: #ffffff;
    flex-shrink: 0;
    padding-left: 1vw;
    font-family: "Montserrat", "Inter", sans-serif;
}

/* Footer */
.dashboard-footer {
    height: 4vh;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    margin-top: 1vh;
}

.footer-text {
    font-size: 1.3vh;
    color: rgba(255, 255, 255, 0.25);
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
    text-transform: uppercase;
    letter-spacing: 0.15em;
}

.footer-text .highlight {
    color: #00a88d;
}
"""

COMPANY_DASHBOARD_JS = """
(function() {
    var canvas = document.getElementById('gridCanvas');
    if (!canvas) return;

    var ctx = canvas.getContext('2d');
    var cellSize = 80;

    // Fixed "mouse" position - TOP-LEFT corner for glow effect
    var fixedMouseX = null;
    var fixedMouseY = null;

    function resizeCanvas() {
        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;

        // Set fixed mouse position after resize - TOP-LEFT area
        fixedMouseX = canvas.width * 0.18;
        fixedMouseY = canvas.height * 0.15;

        drawGrid();
    }

    function drawGrid() {
        ctx.clearRect(0, 0, canvas.width, canvas.height);

        var mouseX = fixedMouseX;
        var mouseY = fixedMouseY;
        var baseAlpha = 0.018;
        var segmentRadius = cellSize * 3.5;

        // Vertical lines
        for (var x = 0; x <= canvas.width; x += cellSize) {
            var dx = (mouseX != null) ? (x - mouseX) : null;
            var distanceFactor = 0;

            if (mouseX != null && mouseY != null) {
                var radialDistance = Math.abs(dx);
                distanceFactor = Math.max(0, 1 - radialDistance / (cellSize * 6));
            }

            var alpha = baseAlpha + distanceFactor * 0.05;
            ctx.strokeStyle = "rgba(255,255,255," + alpha.toFixed(3) + ")";
            ctx.beginPath();
            ctx.moveTo(x + 0.5, 0);
            ctx.lineTo(x + 0.5, canvas.height);
            ctx.stroke();

            // Add colored glow near the fixed point
            if (mouseX != null && mouseY != null && distanceFactor > 0) {
                var chromaIntensity = distanceFactor * 0.25;
                if (Math.abs(dx) < cellSize * 0.5) {
                    chromaIntensity = Math.min(0.6, chromaIntensity * 2);
                }

                var yStart = Math.max(0, mouseY - segmentRadius);
                var yEnd = Math.min(canvas.height, mouseY + segmentRadius);

                // Use teal (#00a88d) on left, pink (#E44398) on right
                var color = (dx < 0) ? "rgba(0,168,141," : "rgba(228,67,152,";
                var grad = ctx.createLinearGradient(0, yStart, 0, yEnd);
                var mid = Math.max(0, Math.min(1, (mouseY - yStart) / (yEnd - yStart)));
                var maxAlpha = chromaIntensity;

                grad.addColorStop(0.0, color + "0)");
                if (mid - 0.15 > 0) grad.addColorStop(mid - 0.15, color + (maxAlpha * 0.3).toFixed(3) + ")");
                if (mid - 0.05 > 0) grad.addColorStop(mid - 0.05, color + (maxAlpha * 0.8).toFixed(3) + ")");
                grad.addColorStop(mid, color + maxAlpha.toFixed(3) + ")");
                if (mid + 0.05 < 1) grad.addColorStop(mid + 0.05, color + (maxAlpha * 0.8).toFixed(3) + ")");
                if (mid + 0.15 < 1) grad.addColorStop(mid + 0.15, color + (maxAlpha * 0.3).toFixed(3) + ")");
                grad.addColorStop(1.0, color + "0)");

                ctx.strokeStyle = grad;
                ctx.beginPath();
                ctx.moveTo(x + 0.5, yStart);
                ctx.lineTo(x + 0.5, yEnd);
                ctx.stroke();
            }
        }

        // Horizontal lines
        for (var y = 0; y <= canvas.height; y += cellSize) {
            var dy = (mouseY != null) ? (y - mouseY) : null;
            var distanceFactorY = 0;

            if (mouseX != null && mouseY != null) {
                var radialDistanceY = Math.abs(dy);
                distanceFactorY = Math.max(0, 1 - radialDistanceY / (cellSize * 4));
            }

            var alphaY = baseAlpha + distanceFactorY * 0.05;
            ctx.strokeStyle = "rgba(255,255,255," + alphaY.toFixed(3) + ")";
            ctx.beginPath();
            ctx.moveTo(0, y + 0.5);
            ctx.lineTo(canvas.width, y + 0.5);
            ctx.stroke();

            // Add colored glow near the fixed point
            if (mouseX != null && mouseY != null && distanceFactorY > 0) {
                var chromaIntensityY = distanceFactorY * 0.25;
                if (Math.abs(dy) < cellSize * 0.5) {
                    chromaIntensityY = Math.min(0.6, chromaIntensityY * 2);
                }

                var xStart = Math.max(0, mouseX - segmentRadius);
                var xEnd = Math.min(canvas.width, mouseX + segmentRadius);

                // Use teal above, white below (subtle)
                var color = (dy < 0) ? "rgba(0,168,141," : "rgba(255,255,255,";
                var grad = ctx.createLinearGradient(xStart, 0, xEnd, 0);
                var mid = Math.max(0, Math.min(1, (mouseX - xStart) / (xEnd - xStart)));
                var maxAlpha = chromaIntensityY;

                if (dy >= 0) {
                    maxAlpha = maxAlpha * 0.4;
                }

                grad.addColorStop(0.0, color + "0)");
                if (mid - 0.15 > 0) grad.addColorStop(mid - 0.15, color + (maxAlpha * 0.3).toFixed(3) + ")");
                if (mid - 0.05 > 0) grad.addColorStop(mid - 0.05, color + (maxAlpha * 0.8).toFixed(3) + ")");
                grad.addColorStop(mid, color + maxAlpha.toFixed(3) + ")");
                if (mid + 0.05 < 1) grad.addColorStop(mid + 0.05, color + (maxAlpha * 0.8).toFixed(3) + ")");
                if (mid + 0.15 < 1) grad.addColorStop(mid + 0.15, color + (maxAlpha * 0.3).toFixed(3) + ")");
                grad.addColorStop(1.0, color + "0)");

                ctx.strokeStyle = grad;
                ctx.beginPath();
                ctx.moveTo(xStart, y + 0.5);
                ctx.lineTo(xEnd, y + 0.5);
                ctx.stroke();
            }
        }
    }

    window.addEventListener('resize', resizeCanvas);
    resizeCanvas();
})();"""


def create_company_dashboard(apps, schema_editor):
    """Create the Company Performance Dashboard screen design."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')

    # Check if it already exists
    if ScreenDesign.objects.filter(slug='company-dashboard').exists():
        # Update existing
        dashboard = ScreenDesign.objects.get(slug='company-dashboard')
        dashboard.name = 'Company Dashboard'
        dashboard.description = 'Company-wide performance dashboard with device targets and trending'
        dashboard.html_code = COMPANY_DASHBOARD_HTML
        dashboard.css_code = COMPANY_DASHBOARD_CSS
        dashboard.js_code = COMPANY_DASHBOARD_JS
        dashboard.is_active = True
        dashboard.save()
    else:
        # Create new
        ScreenDesign.objects.create(
            name='Company Dashboard',
            slug='company-dashboard',
            description='Company-wide performance dashboard with device targets and trending',
            html_code=COMPANY_DASHBOARD_HTML,
            css_code=COMPANY_DASHBOARD_CSS,
            js_code=COMPANY_DASHBOARD_JS,
            is_active=True,
        )


def remove_company_dashboard(apps, schema_editor):
    """Remove the Company Dashboard screen design."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')
    ScreenDesign.objects.filter(slug='company-dashboard').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0046_jumpca_dashboard_center_panel_labels'),
    ]

    operations = [
        migrations.RunPython(create_company_dashboard, remove_company_dashboard),
    ]
