# Generated by Django 4.2

from django.db import migrations

# Updated HTML with separate top5_trending data path
COMPANY_DASHBOARD_HTML_V2 = """<div class="dashboard-container">
    <canvas class="grid-canvas" id="gridCanvas"></canvas>

    <div class="dashboard-content">
        <div class="powered-by">
            <img src="/static/digital_signage/poweredbygrid.png" alt="Powered by The Grid" class="powered-by-logo">
        </div>

        <div class="dashboard-header">
            <img src="/static/digital_signage/jump_logo_white.png" alt="Jump.ca" class="company-logo">
            <p class="dashboard-subtitle">Company Performance Dashboard</p>
        </div>

        <div class="metrics-grid">
            <div class="metric-card">
                <div class="metric-label">Today's Devices</div>
                <div class="metric-value primary">{{sales.today.totals.devices}}</div>
            </div>

            <div class="metric-card">
                <div class="metric-label">MTD Devices</div>
                <div class="metric-value">{{sales.mtd.totals.devices}}</div>
            </div>

            <div class="metric-card">
                <div class="metric-label">% of Target</div>
                <div class="metric-value accent">{{sales.mtd.totals.pct_of_target}}</div>
            </div>

            <div class="metric-card">
                <div class="metric-label">MTD Trending</div>
                <div class="metric-value">{{sales.mtd.totals.trending}}</div>
            </div>
        </div>

        <div class="leaderboard-row">
            <div class="leaderboard-panel">
                <div class="metric-label">Top 5 % of Target</div>
                <div class="leaderboard-list">
                    {{#each sales.mtd.targets.devices.top5}}
                    <div class="leaderboard-item">
                        <div class="rank-badge">{{rank}}</div>
                        <span class="store-name">{{store_name}}</span>
                        <span class="store-value">{{pct_of_target}}</span>
                    </div>
                    {{/each}}
                </div>
            </div>

            <div class="leaderboard-panel">
                <div class="metric-label">Top 5 Trending</div>
                <div class="leaderboard-list">
                    {{#each sales.mtd.targets.devices.top5_trending}}
                    <div class="leaderboard-item">
                        <div class="rank-badge">{{rank}}</div>
                        <span class="store-name">{{store_name}}</span>
                        <span class="store-value">{{trending}}</span>
                    </div>
                    {{/each}}
                </div>
            </div>
        </div>

        <div class="dashboard-footer">
            <span class="footer-text">Data refreshes every <span class="highlight">5 minutes</span></span>
        </div>
    </div>
</div>"""


def update_company_dashboard_trending(apps, schema_editor):
    """Update Company Dashboard to use independent trending ranking."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')

    try:
        dashboard = ScreenDesign.objects.get(slug='company-dashboard')
        dashboard.html_code = COMPANY_DASHBOARD_HTML_V2
        dashboard.save()
    except ScreenDesign.DoesNotExist:
        pass


def revert_company_dashboard_trending(apps, schema_editor):
    """Revert (no-op)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0047_company_dashboard'),
    ]

    operations = [
        migrations.RunPython(update_company_dashboard_trending, revert_company_dashboard_trending),
    ]
