# Generated by Django 4.2

from django.db import migrations

# Updated CSS - remove gold/silver/bronze from second panel
# Updated HTML - show devices alongside percentage

TOP20_PCT_TARGET_HTML_V2 = """<div class="dashboard-container">
    <canvas class="grid-canvas" id="gridCanvas"></canvas>

    <div class="dashboard-content">
        <div class="powered-by">
            <img src="/static/digital_signage/poweredbygrid.png" alt="Powered by The Grid" class="powered-by-logo">
        </div>

        <div class="dashboard-header">
            <img src="/static/digital_signage/jump_logo_white.png" alt="Jump.ca" class="company-logo">
            <p class="dashboard-subtitle">Top 20 Locations - % of Device Target</p>
        </div>

        <div class="leaderboard-row">
            <div class="leaderboard-panel panel-first">
                <div class="metric-label">Ranks 1-10</div>
                <div class="leaderboard-list">
                    {{#each sales.mtd.targets.devices.top10_first}}
                    <div class="leaderboard-item">
                        <div class="rank-badge">{{rank}}</div>
                        <span class="store-name">{{store_name}}</span>
                        <span class="store-devices">{{actual}}</span>
                        <span class="store-value">{{pct_of_target}}</span>
                    </div>
                    {{/each}}
                </div>
            </div>

            <div class="leaderboard-panel panel-second">
                <div class="metric-label">Ranks 11-20</div>
                <div class="leaderboard-list">
                    {{#each sales.mtd.targets.devices.top10_second}}
                    <div class="leaderboard-item">
                        <div class="rank-badge">{{rank}}</div>
                        <span class="store-name">{{store_name}}</span>
                        <span class="store-devices">{{actual}}</span>
                        <span class="store-value">{{pct_of_target}}</span>
                    </div>
                    {{/each}}
                </div>
            </div>
        </div>

        <div class="dashboard-footer">
            <span class="footer-text">Data refreshes every <span class="highlight">5 minutes</span></span>
        </div>
    </div>
</div>"""

TOP20_PCT_TARGET_CSS_V2 = """/* Top 20 % of Target Dashboard - Grid Style V2 */
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Montserrat:wght@400;500;600;700&family=Roboto+Mono:wght@400;500;600;700&display=swap');

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

/* Main container */
.dashboard-container {
    height: 100vh;
    width: 100vw;
    overflow: hidden;
    position: relative;
    background-color: #050506;
}

/* Canvas for interactive grid - fills entire background */
.grid-canvas {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 0;
}

/* Content wrapper above canvas */
.dashboard-content {
    position: relative;
    z-index: 1;
    display: flex;
    flex-direction: column;
    height: 100%;
    padding: 3vh 3vw;
}

/* Powered by badge - single combined image */
.powered-by {
    position: absolute;
    top: 3vh;
    right: 3vw;
    z-index: 10;
}

.powered-by-logo {
    height: 10vh;
    width: auto;
    opacity: 0.6;
}

/* Header - smaller to give more room to leaderboards */
.dashboard-header {
    text-align: center;
    height: 10vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    flex-shrink: 0;
}

.company-logo {
    height: 5vh;
    width: auto;
    margin-bottom: 0.8vh;
}

.dashboard-subtitle {
    font-size: 1.6vh;
    color: rgba(255, 255, 255, 0.45);
    text-transform: uppercase;
    letter-spacing: 0.2em;
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
}

.metric-label {
    font-size: 1.5vh;
    color: rgba(255, 255, 255, 0.45);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 1.5vh;
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
}

/* Center metric-label in leaderboard panels */
.leaderboard-panel .metric-label {
    text-align: center;
    width: 100%;
}

/* Leaderboard Section - Two columns, takes most of screen */
.leaderboard-row {
    flex: 1;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1.5vw;
    min-height: 0;
    overflow: hidden;
    margin-top: 2vh;
}

.leaderboard-panel {
    background: rgba(11, 11, 11, 0.85);
    border: 1px solid rgba(255, 255, 255, 0.08);
    padding: 2vh 2vw;
    display: flex;
    flex-direction: column;
    min-height: 0;
    overflow: hidden;
}

.leaderboard-list {
    display: flex;
    flex-direction: column;
    gap: 0.6vh;
    flex: 1;
    min-height: 0;
    overflow: hidden;
}

.leaderboard-item {
    display: flex;
    align-items: center;
    padding: 0 1.5vw;
    background: rgba(255, 255, 255, 0.02);
    border: 1px solid rgba(255, 255, 255, 0.04);
    flex: 1;
    min-height: 0;
}

/* Rank Badge - Square style */
.rank-badge {
    width: 3.2vh;
    height: 3.2vh;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 1.6vh;
    font-weight: 500;
    color: rgba(255, 255, 255, 0.35);
    background: rgba(255, 255, 255, 0.03);
    border: 1px solid rgba(255, 255, 255, 0.08);
    margin-right: 1.5vw;
    flex-shrink: 0;
    font-family: "Montserrat", "Inter", sans-serif;
}

/* Gold/Silver/Bronze ONLY for first panel (panel-first) */
.panel-first .leaderboard-item:nth-child(1) .rank-badge {
    background: #D4AF37;
    border-color: #D4AF37;
    color: #0b0b0b;
}

.panel-first .leaderboard-item:nth-child(2) .rank-badge {
    background: #C0C0C0;
    border-color: #C0C0C0;
    color: #0b0b0b;
}

.panel-first .leaderboard-item:nth-child(3) .rank-badge {
    background: #A97142;
    border-color: #A97142;
    color: #0b0b0b;
}

.store-name {
    flex: 1;
    font-size: 1.8vh;
    font-weight: 500;
    color: rgba(255, 255, 255, 0.45);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    min-width: 0;
    font-family: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

/* Device count - smaller, muted */
.store-devices {
    font-size: 1.6vh;
    font-weight: 500;
    color: rgba(255, 255, 255, 0.35);
    flex-shrink: 0;
    padding-left: 1vw;
    padding-right: 0.5vw;
    font-family: "Montserrat", "Inter", sans-serif;
}

/* Add "devices" label after the number */
.store-devices::after {
    content: " dev";
    font-size: 1.2vh;
    color: rgba(255, 255, 255, 0.25);
}

.store-value {
    font-size: 2vh;
    font-weight: 500;
    color: #ffffff;
    flex-shrink: 0;
    padding-left: 0.5vw;
    font-family: "Montserrat", "Inter", sans-serif;
}

/* Footer */
.dashboard-footer {
    height: 4vh;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    margin-top: 1vh;
}

.footer-text {
    font-size: 1.3vh;
    color: rgba(255, 255, 255, 0.25);
    font-family: "Roboto Mono", ui-monospace, "SF Mono", monospace;
    text-transform: uppercase;
    letter-spacing: 0.15em;
}

.footer-text .highlight {
    color: #00a88d;
}
"""


def update_top20_pct_target(apps, schema_editor):
    """Update Top 20 % of Target dashboard with fixes."""
    ScreenDesign = apps.get_model('digital_signage', 'ScreenDesign')

    try:
        dashboard = ScreenDesign.objects.get(slug='top20-pct-target')
        dashboard.html_code = TOP20_PCT_TARGET_HTML_V2
        dashboard.css_code = TOP20_PCT_TARGET_CSS_V2
        dashboard.save()
    except ScreenDesign.DoesNotExist:
        pass


def revert_top20_pct_target(apps, schema_editor):
    """Revert (no-op)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signage', '0049_top20_pct_target_dashboard'),
    ]

    operations = [
        migrations.RunPython(update_top20_pct_target, revert_top20_pct_target),
    ]
